M48
; DRILL file {KiCad 9.0.1} date 2025-10-25T16:53:59-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-25T16:53:59-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X161.5Y-33.0
X161.5Y-135.0
X233.0Y-111.0
X245.5Y-33.0
X245.5Y-135.0
M30
