GatorGrid: TCP_NAK_MESSAGE Class Reference
TCP_NAK_MESSAGE Class Reference
#include <Messages.hpp>
Public Member Functions
TCP_NAK_MESSAGE (uint32_t src_id, uint32_t dest_id, uint16_t bytes_received)
uint8_t * get_msg () override
uint16_t get_len () override
void set_error (uint8_t err)
void set_msg (void *msg) override
Public Member Functions inherited from TCP_MESSAGE
TCP_MESSAGE (uint8_t priority)
~TCP_MESSAGE ()
virtual uint8_t * get_msg ()=0
virtual uint16_t get_len ()=0
virtual void set_msg (void *msg)=0
struct __attribute__ ((__packed__)) tcp_init_msg_t
struct __attribute__ ((__packed__)) tcp_update_msg_t
struct __attribute__ ((__packed__)) tcp_data_msg_t
struct __attribute__ ((__packed__)) tcp_disconnect_msg_t
struct __attribute__ ((__packed__)) tcp_acknowledge_msg_t
struct __attribute__ ((__packed__)) tcp_failed_msg_t
struct __attribute__ ((__packed__)) tcp_force_update_msg_t
Public Attributes
tcp_failed_msg msg = {0}
Public Attributes inherited from TCP_MESSAGE
tcp_init_msg
tcp_update_msg
tcp_data_msg
tcp_disconnect_msg
tcp_acknowledge_msg
tcp_failed_msg
tcp_force_update_msg
Additional Inherited Members
Protected Attributes inherited from TCP_MESSAGE
uint8_t priority
Constructor & Destructor Documentation
TCP_NAK_MESSAGE()
TCP_NAK_MESSAGE::TCP_NAK_MESSAGE (uint32_t src_id, uint32_t dest_id, uint16_t bytes_received) inline
                                                                                : TCP_MESSAGE(0xFF) {
        msg.priority = priority;
        msg.msg_id = 0x05;
        msg.len = 15;
        msg.source = src_id;
        msg.dest = dest_id;
        msg.bytes_received = bytes_received;
    }
References msg, and TCP_MESSAGE::priority.
Member Function Documentation
get_len()
uint16_t TCP_NAK_MESSAGE::get_len () inline override virtual
Implements TCP_MESSAGE.
{
        return msg.len;
    }
References msg.
Referenced by STANode::handle_incoming_data(), and APNode::handle_incoming_data().
get_msg()
uint8_t * TCP_NAK_MESSAGE::get_msg () inline override virtual
Implements TCP_MESSAGE.
{
        return reinterpret_cast<uint8_t*>(&msg);
    }
References msg.
Referenced by STANode::handle_incoming_data(), and APNode::handle_incoming_data().
set_error()
void TCP_NAK_MESSAGE::set_error (uint8_t err) inline
{
        msg.error = err;
    }
References msg.
Referenced by APNode::handle_incoming_data().
set_msg()
void TCP_NAK_MESSAGE::set_msg (void * msg) inline override virtual
Implements TCP_MESSAGE.
{
        this->msg = *(reinterpret_cast<tcp_failed_msg*>(msg));
    }
References msg, and TCP_MESSAGE::tcp_failed_msg.
Referenced by parseMessage().
Member Data Documentation
msg
tcp_failed_msg TCP_NAK_MESSAGE::msg = {0}
Referenced by get_len(), get_msg(), set_error(), set_msg(), and TCP_NAK_MESSAGE().
The documentation for this class was generated from the following file:
libraries/MeshNode/Messages.hpp