GatorGrid: SPI Class Reference
SPI Class Reference
#include <SPI.hpp>
Public Member Functions
SPI ()
bool SPI_init ()
void Set_Master (bool master)
int SPI_send_message (std::vector< uint8_t > &message)
void SPI_read_message (std::vector< uint8_t > &response)
bool SPI_POLL_MESSAGE ()
void SPI_deinit_to_gpio ()
Private Attributes
bool is_master
std::vector< uint8_t > response_message
Constructor & Destructor Documentation
SPI()
SPI::SPI ()
{};
Member Function Documentation
Set_Master()
void SPI::Set_Master (bool master)
{
    is_master = master;
}
References is_master.
Referenced by Test1(), and Test2().
SPI_deinit_to_gpio()
void SPI::SPI_deinit_to_gpio ()
{
    // Wait for any in-flight transfer to finish
    while (spi_is_busy(SPI_PORT));
    // Disable the SPI peripheral
    spi_deinit(SPI_PORT);
    // Return pins to GPIO (SIO) and set as inputs with no pulls
    gpio_set_function(PIN_MISO, GPIO_FUNC_SIO);
    gpio_set_function(PIN_MOSI, GPIO_FUNC_SIO);
    gpio_set_function(PIN_SCK,  GPIO_FUNC_SIO);
    gpio_set_function(PIN_CS,   GPIO_FUNC_SIO);
    gpio_disable_pulls(PIN_MISO);
    gpio_disable_pulls(PIN_MOSI);
    gpio_disable_pulls(PIN_SCK);
    gpio_disable_pulls(PIN_CS);
    gpio_set_dir(PIN_MISO, GPIO_IN);
    gpio_set_dir(PIN_MOSI, GPIO_IN);
    gpio_set_dir(PIN_SCK,  GPIO_IN);
    gpio_set_dir(PIN_CS,   GPIO_IN);
    printf("SPI disabled\n");
}
References PIN_CS, PIN_MISO, PIN_MOSI, PIN_SCK, and SPI_PORT.
Referenced by SPI_POLL_MESSAGE(), and SPI_send_message().
SPI_init()
bool SPI::SPI_init ()
Initialize the SPI module by passing in whether the node is a slave (false) or master (true)
                  {
    if(is_master){
        printf("Setting up SPI Master\n");
        // Setting up the Master
        spi_init(SPI_PORT, 1000 * 1000);
        spi_set_slave(SPI_PORT, false);
    }
    else{
        printf("Setting up SPI Slave\n");
        // Set as slave
        spi_init(SPI_PORT, 1000 * 1000);
        spi_set_slave(SPI_PORT, true);
    }
    gpio_set_function(PIN_SCK, GPIO_FUNC_SPI);
    gpio_set_function(PIN_MISO, GPIO_FUNC_SPI);
    gpio_set_function(PIN_MOSI, GPIO_FUNC_SPI);
    gpio_set_function(PIN_CS, GPIO_FUNC_SPI);
    printf("SPI initialized successfully\n");
    return true;
};
References is_master, PIN_CS, PIN_MISO, PIN_MOSI, PIN_SCK, and SPI_PORT.
Referenced by main(), SPI_POLL_MESSAGE(), and SPI_send_message().
SPI_POLL_MESSAGE()
bool SPI::SPI_POLL_MESSAGE ()
Function to poll for messages
{
    puts("polling");
    if(is_master){
       // Master specific polling
       // Check if MISO is high
        if(gpio_get(PIN_MISO_MASTER)){
            gpio_init(PIN_MOSI_MASTER);
           // Assert MOSI to high
           gpio_set_dir(PIN_MOSI_MASTER, GPIO_OUT);
           gpio_put(PIN_MOSI_MASTER, 1);
           // short delay for stabilization
           sleep_ms(10);
           // Delay to wait for slave to initialize
           sleep_ms(110);
           SPI_init();
           // message of 32 char f
           std::vector<uint8_t> message = { 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f',
                                              'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f',
                                              'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f',
                                              'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f' };
           std::vector<uint8_t> response(message.size());
           spi_write_read_blocking(SPI_PORT, message.data(), response.data(), message.size());
            while(spi_is_busy(SPI_PORT));
            response_message = response;
            // deinitialize SPI
            SPI_deinit_to_gpio();
            return true;
       }
   }
   else{
       // Slave specific polling
       // Check if MOSI is high
       printf("Waiting for MOSI to go High\n");
       // print status of MOSI
       printf("MOSI Status: %d\n", gpio_get(PIN_MOSI_SLAVE));
       if(gpio_get(PIN_MOSI_SLAVE)){
           // Assert MISO to high
           gpio_init(PIN_MISO_SLAVE);
           gpio_set_dir(PIN_MISO_SLAVE, GPIO_OUT);
           gpio_put(PIN_MISO_SLAVE, 1);
            // print status of MISO
           printf("MISO Status: %d\n", gpio_get(PIN_MISO_SLAVE));
           // short delay
           sleep_ms(10);
           // init spi
           SPI_init();
           // message of 32 char f
           std::vector<uint8_t> message = { 'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f',
                                              'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f',
                                              'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f',
                                              'f', 'f', 'f', 'f', 'f', 'f', 'f', 'f' };
           std::vector<uint8_t> response(message.size());
           spi_write_read_blocking(SPI_PORT, message.data(), response.data(), message.size());
            //while(spi_is_busy(SPI_PORT));
            response_message = response;
            // deinitialize SPI
            SPI_deinit_to_gpio();
            return true;
       }
   }
   return false;
}
References is_master, PIN_MISO_MASTER, PIN_MISO_SLAVE, PIN_MOSI_MASTER, PIN_MOSI_SLAVE, response_message, SPI_deinit_to_gpio(), SPI_init(), and SPI_PORT.
Referenced by Test1(), and Test2().
SPI_read_message()
void SPI::SPI_read_message (std::vector< uint8_t > & response)
Function to read a message that was sent from SPI by passing in a byte pointer and its size to store result.
{
    response = response_message;
};
References response_message.
Referenced by main(), Test1(), and Test2().
SPI_send_message()
int SPI::SPI_send_message (std::vector< uint8_t > & message)
Function to send a message
{
    if(is_master){
        // Master specific behavior
        gpio_init(PIN_MOSI_MASTER);
        // Set MOSI direction to output
        gpio_set_dir(PIN_MOSI_MASTER, GPIO_OUT);
        gpio_set_dir(PIN_MISO_MASTER, GPIO_IN);
        // Assert MOSI high
        gpio_put(PIN_MOSI_MASTER, 1);
        printf("Asserted MOSI High\n");
        // print status of MOSI
        printf("MOSI Status: %d\n", gpio_get(PIN_MOSI_MASTER));
        // short delay for stabilization
        //sleep_ms(10);
        printf("Waiting for MISO to go High\n");
        // wait for MISO to be high
        while(!gpio_get(PIN_MISO_MASTER)) {
            puts("Master polling for slave to be ready");
        }
        printf("Deasserting MOSI\n");
        // Deassert MOSI
        gpio_put(PIN_MOSI_MASTER, 0);
        // short delay for stabilization
        sleep_ms(10);
        // Turn SPI on
        SPI_init();
        // Delay for Slave to initialize
        sleep_ms(110);
        printf("Sending Data: ");
        for(char c : message){
            printf("%c", c);
        }
        printf("\n");
        // Buffer for response
        std::vector<uint8_t> response(message.size());
        spi_write_read_blocking(SPI_PORT, message.data(), response.data(), message.size());
        while(spi_is_busy(SPI_PORT));
        printf("Data Sent!\n");
        printf("Response Data: ");
        for(char c : response){
            printf("%c", c);
        }
        printf("\n");
        // turn off SPI
        SPI_deinit_to_gpio();
    }
    else{
        // Slave specific behavior
        gpio_init(PIN_MISO_SLAVE);
        // Set MISO direction to output
        gpio_set_dir(PIN_MISO_SLAVE, GPIO_OUT);
        gpio_set_dir(PIN_MOSI_SLAVE, GPIO_IN);
        // Assert MISO high
        gpio_put(PIN_MISO_SLAVE, 1);
        printf("Asserted MISO High\n");
        // short delay for stabilization
        sleep_ms(10);
        printf("Waiting for MOSI to go High\n");
        // wait for MOSI to be high
        while(!gpio_get(PIN_MOSI_SLAVE));
        // Deassert MISO
        gpio_put(PIN_MISO_SLAVE, 0);
        // short delay for stabilization
        sleep_ms(10);
        // initialize SPI
        SPI_init();
        printf("Sending Data: ");
        for(char c : message){
            printf("%c", c);
        }
        printf("\n");
        // buffer for the response
        std::vector<uint8_t> response(message.size());
        spi_write_read_blocking(SPI_PORT, message.data(), response.data(), message.size());
        while(spi_is_busy(SPI_PORT));
        printf("Data Sent!\n");
        printf("Response Data: ");
        for(char c : response){
            printf("%c", c);
        }
        printf("\n");
        // turn off SPI
        SPI_deinit_to_gpio();
    }
    return 1;
};
References is_master, PIN_MISO_MASTER, PIN_MISO_SLAVE, PIN_MOSI_MASTER, PIN_MOSI_SLAVE, SPI_deinit_to_gpio(), SPI_init(), and SPI_PORT.
Referenced by main(), Test1(), and Test2().
Member Data Documentation
is_master
bool SPI::is_master private
Referenced by Set_Master(), SPI_init(), SPI_POLL_MESSAGE(), and SPI_send_message().
response_message
std::vector<uint8_t> SPI::response_message private
Referenced by SPI_POLL_MESSAGE(), and SPI_read_message().
The documentation for this class was generated from the following files:
libraries/SPI/SPI.hpp
libraries/SPI/SPI.cpp