GatorGrid: ChildrenTree Class Reference
ChildrenTree Class Reference
#include <ChildrenTree.hpp>
Classes
struct Node
Public Member Functions
ChildrenTree (uint32_t id)
~ChildrenTree ()
bool add_child (uint32_t child_id)
bool add_any_child (uint32_t parent_id, uint32_t child_id)
void remove_children (int id)
bool remove_child (uint32_t id)
bool update_node (uint32_t id, uint32_t children_id[4], uint8_t &number_of_children)
void edit_head (uint32_t new_id)
bool get_children (uint32_t parent_id, uint32_t children_id[4], uint8_t &number_of_children)
Get the list of children id from a given parent.
Node * find_node (uint32_t id, Node *head)
bool node_exists (uint32_t id)
bool find_path_parent (uint32_t id, uint32_t *parent)
Returns true or false if path exists, and parent is overwritten as the path's parent.
bool find_parent_recursive (Node *node, uint32_t target)
void traverse ()
void get_node_details (ChildrenTree *tree)
std::string serialize_node (Node *node)
std::string serialize_tree ()
void send_tree_serial ()
Private Attributes
Node * head
uint32_t id
Constructor & Destructor Documentation
ChildrenTree()
ChildrenTree::ChildrenTree (uint32_t id) inline
                              : id(id) {
        head = new Node(id);
    }
References head.
~ChildrenTree()
ChildrenTree::~ChildrenTree ()
{
    if (!head) {
        return;
    }
    remove_children(head->id);
    delete head;
    head = nullptr;
}
References head, ChildrenTree::Node::id, and remove_children().
Member Function Documentation
add_any_child()
bool ChildrenTree::add_any_child (uint32_t parent_id, uint32_t child_id)
{
    if(head == nullptr) {return false;}
    Node *parent = find_node(parent_id, head);
    if (parent ==  nullptr) {return false;}
    std::cout << "found parent node\n";
    if (parent->number_of_children > 3) {
        std::cout<<"Max number of children already reached for node " << parent->id;
        return false;
    }
    Node* child = new Node(child_id);
    std::cout << "Made new node\n";
    parent->children[parent->number_of_children] = child;
    parent->number_of_children++;
    child->parent = parent;
    return true;
}
References ChildrenTree::Node::children, find_node(), head, ChildrenTree::Node::id, ChildrenTree::Node::number_of_children, and ChildrenTree::Node::parent.
Referenced by APNode::handle_incoming_data(), STANode::handle_serial_message(), main(), remove_children(), and update_node().
add_child()
bool ChildrenTree::add_child (uint32_t child_id)
{
    if(head == nullptr) {return false;}
    Node* child = new Node(child_id);
    Node* temp;
    std::vector<Node*> nodes;
    nodes.push_back(head);
    bool found = false;
    while(!found && !nodes.empty()) {
        temp = nodes.back();
        if (temp->number_of_children < 4) {
            found = true;
            child->parent = temp;
            temp->children[temp->number_of_children] = child;
            temp->number_of_children++;
        }
        else {
            for (int i = 0; i < temp->number_of_children; i++) {
                nodes.insert(nodes.begin(), temp->children[i]);
            }
        }
        nodes.pop_back();
    }
    nodes.clear();
    return found;
}
References ChildrenTree::Node::children, head, ChildrenTree::Node::number_of_children, and ChildrenTree::Node::parent.
Referenced by STANode::handle_incoming_data(), and main().
edit_head()
void ChildrenTree::edit_head (uint32_t new_id)
{
    head->id = new_id;
}
References head, and ChildrenTree::Node::id.
Referenced by STANode::init_sta_mode().
find_node()
ChildrenTree::Node * ChildrenTree::find_node (uint32_t id, Node * head)
{
    if (head == nullptr) {return nullptr;}
    if (head->id == id) {return head;}
    if (head->number_of_children == 0) {
        return nullptr;
    }
    for (int i = 0; i < head->number_of_children; i++) {
        if (head->children[i]->id == id) {
            return head->children[i];
        } else {
            Node* ret_val = find_node(id, head->children[i]);
            if (ret_val) {
                return ret_val;
            }
        }
    }
    return nullptr;
}
References ChildrenTree::Node::children, find_node(), head, ChildrenTree::Node::id, and ChildrenTree::Node::number_of_children.
Referenced by add_any_child(), find_node(), get_children(), node_exists(), remove_children(), and update_node().
find_parent_recursive()
bool ChildrenTree::find_parent_recursive (Node * node, uint32_t target)
{
    for (int i = 0; i < node->number_of_children; ++i) {
        Node* child = node->children[i];
        if (!child) continue;
        if (child->id == target) {
            // this node is the parent of the target
            return true;
        }
        // otherwise, recurse into that child’s subtree
        if (find_parent_recursive(child, target)) {
            return true;
        }
    }
    return false;
}
References ChildrenTree::Node::children, find_parent_recursive(), ChildrenTree::Node::id, and ChildrenTree::Node::number_of_children.
Referenced by find_parent_recursive(), and find_path_parent().
find_path_parent()
bool ChildrenTree::find_path_parent (uint32_t id, uint32_t * parent)
Returns true or false if path exists, and parent is overwritten as the path's parent.
Parameters
id node to find
parent of the path to node to find
Returns
true
false
{
    DEBUG_printf("Checking tree for parent of the path to %u\n", id);
    if (!head) {
        // either empty tree or id not in tree
        ERROR_printf("head == nullptr");
        return false;
    }
    DEBUG_printf("Children count of head %d", head->number_of_children);
    for (int i = 0; i < head->number_of_children; i++) {
        Node* child = head->children[i];
        if (!child) continue;
        if (child->id == id) {
            *parent = child->id;
            return true;
        }
        else if (find_parent_recursive(child, id)) {
            *parent = child->id;
            return true;
        }
    }
    ERROR_printf("Failed to find path_parent, parent set to -1");
    *parent = UINT32_MAX;
    return false;
}
References ChildrenTree::Node::children, DEBUG_printf, ERROR_printf, find_parent_recursive(), head, ChildrenTree::Node::id, and ChildrenTree::Node::number_of_children.
Referenced by APNode::handle_incoming_data(), STANode::handle_incoming_data(), APNode::send_msg(), and STANode::send_msg().
get_children()
bool ChildrenTree::get_children (uint32_t parent_id, uint32_t children_id[4], uint8_t & number_of_children)
Get the list of children id from a given parent.
Parameters
[in] parent_id
[out] children_id - must be allocated for max number of children - 4
[out] number_of_children
Returns
true parent node found
false parent node not found
{
    Node* node = find_node(parent_id, head);
    if (!node) return false;
    for (int i = 0; i < node->number_of_children; i++) {
        children_id[i] = node->children[i]->id;
    }
    number_of_children = node->number_of_children;
    return true;
}
References ChildrenTree::Node::children, find_node(), head, ChildrenTree::Node::id, and ChildrenTree::Node::number_of_children.
Referenced by STANode::handle_serial_message(), main(), and STANode::update_network().
get_node_details()
void ChildrenTree::get_node_details (ChildrenTree * tree)
{
    Node* node = tree->head;
    if (node == this->head) {
        std::cout << "Head\n";
    }
    else {
        std::cout << "Not Head\n";
    }
    std::cout << "Number of Children: "<<(int)node->number_of_children;
    if(node->number_of_children == 0) std::cout << "No Children";
    std::cout << "\nID: " << node->id;
}
References head, ChildrenTree::Node::id, and ChildrenTree::Node::number_of_children.
node_exists()
bool ChildrenTree::node_exists (uint32_t id)
{
    if (find_node(id, head) != nullptr) {
        return true;
    }
    return false;
}
References find_node(), and head.
Referenced by APNode::handle_incoming_data(), and main().
remove_child()
bool ChildrenTree::remove_child (uint32_t id)
remove_children()
void ChildrenTree::remove_children (int id)
{
    Node* node = this->find_node(id, this->head);
    for (int i = 0; i < node->number_of_children; i++) {
        for (int j = 0; j < node->children[i]->number_of_children; j++) {
            int childId = node->children[i]->id;
            add_any_child(node->id, childId);
            delete node->children[i]->children[j];
        }
        remove_children(node->children[i]->id);
        delete node->children[i];
    }
    node->number_of_children = 0;
}
References add_any_child(), ChildrenTree::Node::children, find_node(), head, ChildrenTree::Node::id, ChildrenTree::Node::number_of_children, and remove_children().
Referenced by remove_children(), and ~ChildrenTree().
send_tree_serial()
void ChildrenTree::send_tree_serial ()
{
    std::string json = serialize_tree();
    printf("%s\n", json.c_str());   // prints JSON over USB serial (Pico default)
}
References serialize_tree().
Referenced by main().
serialize_node()
std::string ChildrenTree::serialize_node (Node * node)
{
    std::ostringstream ss;
    ss << "{\"id\":" << node->id << ",\"children\":[";
    for (int i = 0; i < node->number_of_children; i++) {
        if (i > 0) ss << ",";
        ss << serialize_node(node->children[i]);
    }
    ss << "]}";
    return ss.str();
}
References ChildrenTree::Node::children, ChildrenTree::Node::id, ChildrenTree::Node::number_of_children, and serialize_node().
Referenced by serialize_node(), and serialize_tree().
serialize_tree()
std::string ChildrenTree::serialize_tree ()
{
    if (!head) return "{}";
    return serialize_node(head);
}
References head, and serialize_node().
Referenced by send_tree_serial().
traverse()
void ChildrenTree::traverse ()
{
    Node *root = this->head;
    if (root == nullptr) {
        return;
    }
    std::vector<Node*> queue;
    queue.push_back(root);
    while (!queue.empty()) {
        Node* current = queue.front();
        queue.erase(queue.begin());
        std::cout << "\nNode ID: " << current->id << " | Children: " << (int)current->number_of_children << " | Parent ID: " << (current->parent ? std::to_string(current->parent->id) : "None") <<std::endl;
        if (current->children != nullptr) {
            for (int i = 0; i < current->number_of_children; ++i) {
                queue.push_back(current->children[i]);
            }
        }
    }
}
References ChildrenTree::Node::children, head, ChildrenTree::Node::id, ChildrenTree::Node::number_of_children, and ChildrenTree::Node::parent.
update_node()
bool ChildrenTree::update_node (uint32_t id, uint32_t children_id[4], uint8_t & number_of_children)
{
    Node* node = find_node(id, head);
    if (!node) {
        ERROR_printf("Node with id: %u not found", id);
        return false;
    }
    for (int i = 0; i < number_of_children; i++) {
        bool found = false;
        for (int j = 0; j < node->number_of_children; j++) {
            if (node->children[j]->id == children_id[i]) {
                found = true;
                break;
            }
        }
        if (found) continue;
        if (!add_any_child(node->id, children_id[i])) return false;
    }
    return true;
}
References add_any_child(), ChildrenTree::Node::children, ERROR_printf, find_node(), head, ChildrenTree::Node::id, and ChildrenTree::Node::number_of_children.
Referenced by STANode::handle_incoming_data().
Member Data Documentation
head
Node* ChildrenTree::head private
Referenced by add_any_child(), add_child(), ChildrenTree(), edit_head(), find_node(), find_path_parent(), get_children(), get_node_details(), node_exists(), remove_children(), serialize_tree(), traverse(), update_node(), and ~ChildrenTree().
id
uint32_t ChildrenTree::id private
The documentation for this class was generated from the following files:
libraries/ChildrenTree/ChildrenTree.hpp
libraries/ChildrenTree/ChildrenTree.cpp