GatorGrid: STANode Class Reference
STANode Class Reference
#include <MeshNode.hpp>
Public Member Functions
STANode ()
~STANode ()
bool init_sta_mode ()
bool start_sta_mode ()
bool scan_for_nodes ()
bool connect_to_node (uint32_t id)
bool connect_to_network ()
bool is_connected ()
bool tcp_init ()
err_t send_data (uint32_t send_id, ssize_t len, uint8_t *buf)
bool send_tcp_data (uint8_t *data, uint32_t size, bool forward)
bool send_tcp_data_blocking (uint8_t *data, uint32_t size, bool forward)
Will wait until availble to send tcp, then will wait for an ACK response before releasing.
struct data digest_data ()
int number_of_messages ()
bool handle_incoming_data (unsigned char *buffer, uint16_t tot_len)
err_t send_msg (uint8_t *msg)
err_t handle_serial_message (uint8_t *msg)
err_t update_network ()
void poll ()
Public Member Functions inherited from MeshNode
MeshNode ()
virtual ~MeshNode ()
void set_NodeID (uint32_t ID)
uint32_t get_NodeID ()
void seed_rand ()
bool get_is_root ()
void set_is_root (bool status)
Static Public Member Functions
static int scan_result (void *env, const cyw43_ev_scan_result_t *result)
Public Attributes
std::map< int, cyw43_ev_scan_result_t * > known_nodes
uint32_t parent
TCP_CLIENT_T * state
std::string AP_CONNECTED_IP
RingBuffer rb
ChildrenTree tree
PicoUART uart
Public Attributes inherited from MeshNode
bool is_root = false
Constructor & Destructor Documentation
STANode()
STANode::STANode ()
                 : rb(10), tree(0) {
    // Use hardware-based entropy sources if possible
    uint32_t ID = 0;
    // set the NodeID variable
    set_NodeID(ID);
   DEBUG_printf("Node ID is initially set to 0!\n");
    // Set SPI to be a slave
    DEBUG_printf("starting uart\n");
    uart.picoUARTInit();
    DEBUG_printf("uart initalized\n");
    uart.picoUARTInterruptInit();
    DEBUG_printf("uart intterupts initalized\n");
    known_nodes.clear();
    parent = UINT32_MAX;
}
References DEBUG_printf, known_nodes, parent, PicoUART::picoUARTInit(), PicoUART::picoUARTInterruptInit(), MeshNode::set_NodeID(), and uart.
~STANode()
STANode::~STANode ()
                  {
    for (auto it = known_nodes.begin(); it != known_nodes.end(); it++)
    {
        free(it->second);
    }
}
References known_nodes.
Member Function Documentation
connect_to_network()
bool STANode::connect_to_network ()
{
    if (known_nodes.size() == 0) return false;
    scan_for_nodes();
    DEBUG_printf("Knows some nodes\n");
    int16_t min_rssi = known_nodes.begin()->second->rssi;
    uint32_t min_node_id = known_nodes.begin()->first;
    for (const auto& node : known_nodes) {
        if (node.second->rssi > min_rssi) {
            min_rssi = node.second->rssi;
            min_node_id = node.first;
        }
    }
    char ssid[32];  // Allocate on stack instead of heap
    snprintf(ssid, sizeof(ssid), "GatorGrid_Node:%08X", min_node_id);  // Convert ID to uppercase hex
    DEBUG_printf("Generated SSID: %s\n", ssid);
    // Attempt to connect
    if (cyw43_arch_wifi_connect_timeout_ms(ssid, "password", CYW43_AUTH_WPA2_AES_PSK, 20000)) {
        for (int i = 0; i < 20; i++) {
           DEBUG_printf("Failed to connect. Retrying...\n");
            sleep_ms(1000);
        }
        return false;
    }
    DEBUG_printf("Connected successfully.\n");
    parent = min_node_id;
    return true;
}
References DEBUG_printf, known_nodes, parent, and scan_for_nodes().
Referenced by main().
connect_to_node()
bool STANode::connect_to_node (uint32_t id)
{
   DEBUG_printf("Connecting to node: %u\n", id);
    // Check if node is known
    if (known_nodes.count(id) == 0) {
       DEBUG_printf("Unknown node. Ending connection attempt.\n");
        return false;
    }
    // Generate SSID string
    char ssid[32];  // Allocate on stack instead of heap
    snprintf(ssid, sizeof(ssid), "GatorGrid_Node:%08X", id);  // Convert ID to uppercase hex
   DEBUG_printf("Generated SSID: %s\n", ssid);
    // Attempt to connect
    if (cyw43_arch_wifi_connect_timeout_ms(ssid, "password", CYW43_AUTH_WPA2_AES_PSK, 7500)) {
        for (int i = 0; i < 8; i++) {
           DEBUG_printf("Failed to connect. Retrying...\n");
            sleep_ms(1000);
        }
        return false;
    }
   DEBUG_printf("Connected successfully.\n");
    parent = id;
    return true;
}
References DEBUG_printf, known_nodes, and parent.
Referenced by main().
digest_data()
struct data STANode::digest_data ()
{
    return this->rb.digest();
}
handle_incoming_data()
bool STANode::handle_incoming_data (unsigned char * buffer, uint16_t tot_len)
{
    uint32_t source_id = 0;
    bool ACK_flag = false;
    bool NAK_flag = false;
    bool self_reply = false;
    bool send_to_ap = false;
    state->got_nak = false;
    // TCP_MESSAGE* msg = parseMessage(reinterpret_cast <uint8_t *>(buffer));
    // if (!msg) {
    //    DEBUG_printf("Error: Unable to parse message (invalid buffer or unknown msg_id).\n");
    //     ACK_flag = false;
    // } else {
    uint8_t msg_id = buffer[1];
    uint16_t len = *reinterpret_cast<uint16_t*>(buffer +2);
    DEBUG_printf("DUMPING STATE BUFFER BELOW:\n");
    DUMP_BYTES(state->buffer, 200);
    DEBUG_printf("DUMPING BYTES RECV BELOW:\n");
    DUMP_BYTES(buffer, 200);
    //dump_bytes(buffer, 100);
    switch (msg_id) {
        case 0x00: {
            TCP_INIT_MESSAGE initMsg;// = reinterpret_cast<TCP_INIT_MESSAGE*>(buffer);
            initMsg.set_msg(buffer);
            //does stuff
            DEBUG_printf("Received initialization message from node %u", initMsg.msg.source);
            source_id =  initMsg.msg.source;
            tree.add_child(source_id);
            break;
        }
        case 0x01: {
            TCP_DATA_MSG dataMsg;
            dataMsg.set_msg(buffer);
            DEBUG_printf("Got data message\n");
            if (dataMsg.msg.dest == get_NodeID()) {
                source_id =  dataMsg.msg.source;
                rb.insert(dataMsg.msg.msg,dataMsg.msg.msg_len, dataMsg.msg.source, dataMsg.msg.dest);
                DEBUG_printf("Testing dataMsg, len:%u, source:%08x, dest:%08x\n",dataMsg.msg.msg_len, dataMsg.msg.source, dataMsg.msg.dest);
                DEBUG_printf("DBG: Received message from node %08x: %s", dataMsg.msg.source, (char*)dataMsg.msg.msg);
                ACK_flag = true;
                break;
            } else {
                uint32_t path = 0;
                if (tree.find_path_parent(dataMsg.msg.dest, &path)) { // if true, needs to be passed on to AP
                    send_to_ap = true;
                } else {
                    send_msg(dataMsg.get_msg());
                }
            }
            //does stuff
            break;
        }
        case 0x02: {
            TCP_DISCONNECT_MSG initMsg;// = reinterpret_cast<TCP_DISCONNECT_MSG*>(buffer);
            initMsg.set_msg(buffer);
            //does stuff
            break;
        }
        case 0x03: {
            TCP_UPDATE_MESSAGE updateMsg;// = reinterpret_cast<TCP_UPDATE_MESSAGE*>(buffer);
            updateMsg.set_msg(buffer);
            DEBUG_printf("Update packet recieved\n");
            uint32_t id_buffer[4];
            MEMCPY(id_buffer, updateMsg.msg.children_IDs, sizeof(id_buffer));
            if(!tree.update_node(updateMsg.msg.source, id_buffer, updateMsg.msg.child_count)) {
                ERROR_printf("Failed to update node");
            }
            //does stuff
            break;
        }
        case 0x04: {
            DEBUG_printf("Got ACK\n");
            TCP_ACK_MESSAGE ackMsg;// = reinterpret_cast<TCP_ACK_MESSAGE*>(buffer);
            ackMsg.set_msg(buffer);
            source_id = ackMsg.msg.source;
            uint32_t path_parent = 0;
            DEBUG_printf("Ack is from %08x and for %08x\n", ackMsg.msg.source, ackMsg.msg.dest);
            if (ackMsg.msg.dest == get_NodeID()) {
                self_reply = true;
                DEBUG_printf("ACK is for me\n");
                state->waiting_for_ack = false;
            } else if (tree.find_path_parent(ackMsg.msg.dest, &path_parent)) {
                send_to_ap = true;
            } else {
                send_msg(buffer);
            }
            //does stuff
            break;
        }
        case 0x05: {
            TCP_NAK_MESSAGE nakMsg;// = reinterpret_cast<TCP_NAK_MESSAGE*>(buffer);
            nakMsg.set_msg(buffer);
            //does stuff
            DEBUG_printf("Warning! Message was not received! (Got a NAK instead of ACK)");
            DEBUG_printf("Got NAK\n");
            self_reply = true;
            state->waiting_for_ack = false;
            state->got_nak = true;
            break;
        }
        default:
            DEBUG_printf("Error: Unable to parse message (invalid buffer or unknown msg_id).\n");
            ACK_flag = false;
            // SEND NAK message
            //TCP_NAK_MESSAGE nakMsg(node->get_NodeID(), msg_id ? msg_id : 0, 0);
            break;
    }
    if (send_to_ap) {
        DEBUG_printf("Transferring message to AP node");
        uint8_t msg_id = buffer[1];
        SERIAL_DATA_MESSAGE msg;
        msg.add_message(buffer, buffer[2]);
        uart.sendMessage((char*) msg.get_msg());
        //TCP_NAK_MESSAGE* nakMsg = static_cast<TCP_NAK_MESSAGE*>(msg);
        // uart.sendMessage();
        return true;
    }
    if (ACK_flag && !self_reply){
        DEBUG_printf("Sending ack to %08x\n", source_id);
        TCP_ACK_MESSAGE ackMsg(get_NodeID(), source_id, tot_len);
        send_tcp_data(ackMsg.get_msg(), ackMsg.get_len(), true);
        //state->waiting_for_ack = true;
    } else if (NAK_flag) {
        // TODO: Update for error handling
        // identify the source from sender and send back?
        TCP_NAK_MESSAGE nakMsg(get_NodeID(), 0, tot_len);
        send_tcp_data(nakMsg.get_msg(), nakMsg.get_len(), true);
        // delete msg;
        return false;
    }
    // delete msg;
    return true;
}
References ChildrenTree::add_child(), SERIAL_DATA_MESSAGE::add_message(), TCP_CLIENT_T_::buffer, DEBUG_printf, DUMP_BYTES, ERROR_printf, ChildrenTree::find_path_parent(), TCP_ACK_MESSAGE::get_len(), TCP_NAK_MESSAGE::get_len(), TCP_DATA_MSG::get_msg(), TCP_ACK_MESSAGE::get_msg(), TCP_NAK_MESSAGE::get_msg(), SERIAL_DATA_MESSAGE::get_msg(), MeshNode::get_NodeID(), TCP_CLIENT_T_::got_nak, RingBuffer::insert(), TCP_INIT_MESSAGE::msg, TCP_DATA_MSG::msg, TCP_UPDATE_MESSAGE::msg, TCP_ACK_MESSAGE::msg, rb, send_msg(), send_tcp_data(), PicoUART::sendMessage(), TCP_INIT_MESSAGE::set_msg(), TCP_DATA_MSG::set_msg(), TCP_DISCONNECT_MSG::set_msg(), TCP_UPDATE_MESSAGE::set_msg(), TCP_ACK_MESSAGE::set_msg(), TCP_NAK_MESSAGE::set_msg(), state, tree, uart, ChildrenTree::update_node(), and TCP_CLIENT_T_::waiting_for_ack.
Referenced by handle_serial_message(), and tcp_client_recv().
handle_serial_message()
err_t STANode::handle_serial_message (uint8_t * msg)
{
    uint8_t id = serialMessageType(msg);
    DEBUG_printf("Received serial message in handler\n");
    DUMP_BYTES(msg, msg[1]);
    // TODO: Finish switch-case
    switch (id) {
        case 0x00: /* serial_node_add_msg */
        {
            DEBUG_printf("Received serial node add message");
            // If STA receives node_add, a child has been added.
            SERIAL_NODE_ADD_MESSAGE initMsg;
            initMsg.set_msg(msg);
            tree.add_any_child(initMsg.msg.parent, initMsg.msg.child);
            DEBUG_printf("Child successfully added");
            uint32_t children[4];
            uint8_t children_count = 0;
            if (!tree.get_children(initMsg.msg.parent, children, children_count))
            {
                DEBUG_printf("Get children failed :(");
                return -1;
                //idk die or something
                // TODO: failure states
            }
            DEBUG_printf("Sending Update Msg");
            TCP_UPDATE_MESSAGE updateMsg(initMsg.msg.parent, parent);
            updateMsg.add_children(children_count, children);
            return(send_msg(updateMsg.get_msg()));
        }
        case 0x01: /* serial_node_remove_msg */
            // If AP receives node_remove, a parent has been removed
            break;
        case 0x02: /* Data message */
        {
            DEBUG_printf("Got DATA SERIAL MESSAGE\n");
            SERIAL_DATA_MESSAGE serial_msg;
            serial_msg.set_msg(msg);
            handle_incoming_data(serial_msg.get_data(),serial_msg.get_data_len());
            break;
        }
        case 0x03: /* serial_fatal_error_msg */
        {
            break;
        }
        default:
        {
            return 0;
        }
    }
    return 0;
}
References ChildrenTree::add_any_child(), TCP_UPDATE_MESSAGE::add_children(), DEBUG_printf, DUMP_BYTES, ChildrenTree::get_children(), SERIAL_DATA_MESSAGE::get_data(), SERIAL_DATA_MESSAGE::get_data_len(), TCP_UPDATE_MESSAGE::get_msg(), handle_incoming_data(), SERIAL_NODE_ADD_MESSAGE::msg, parent, send_msg(), serialMessageType(), SERIAL_NODE_ADD_MESSAGE::set_msg(), SERIAL_DATA_MESSAGE::set_msg(), and tree.
Referenced by poll().
init_sta_mode()
bool STANode::init_sta_mode ()
{
    uint32_t AP_ID = 0;
    // Wait for the AP pico to send the first message
    DEBUG_printf("Waiting for ID from AP over UART\n");
    while(!uart.BufferReady()) {
        sleep_ms(10);
    }
    uint8_t *buffer = uart.getReadBuffer();
    AP_ID = *(uint32_t*)buffer;
    DEBUG_printf("ID char: %d\n", AP_ID);
    tree.edit_head(AP_ID);
    this->set_NodeID(AP_ID);
    DEBUG_printf("STA new ID is: %08x\n", get_NodeID());
    if (cyw43_arch_init()) {
       DEBUG_printf("failed to initialise\n");
        return false;
    }
     // Set power mode to high power
    if(cyw43_wifi_pm(&cyw43_state, CYW43_PERFORMANCE_PM) != 0) {
        while(true) {
            DEBUG_printf("Failed to set power state\n");
            sleep_ms(1000);
        }
    }
   DEBUG_printf("Initiation to STA mode successful\n");
    return true;
}
References PicoUART::BufferReady(), DEBUG_printf, ChildrenTree::edit_head(), MeshNode::get_NodeID(), PicoUART::getReadBuffer(), MeshNode::set_NodeID(), tree, and uart.
Referenced by core1_entry(), and main().
is_connected()
bool STANode::is_connected ()
{
    int res = cyw43_wifi_link_status(&cyw43_state, CYW43_ITF_STA);
    if (res != CYW43_LINK_JOIN) {
        //DEBUG_printf("%d\n", res);
      return false;
    }
    return true;
}
Referenced by main().
number_of_messages()
int STANode::number_of_messages ()
{
    return this->rb.get_size();
}
References RingBuffer::get_size(), and rb.
poll()
void STANode::poll ()
                   {
    if(uart.BufferReady()) {
        handle_serial_message(uart.getReadBuffer());
    }
}
References PicoUART::BufferReady(), PicoUART::getReadBuffer(), handle_serial_message(), and uart.
Referenced by main().
scan_for_nodes()
bool STANode::scan_for_nodes ()
{
    known_nodes.clear();
    // Check if a scan is already in progress
    if (cyw43_wifi_scan_active(&cyw43_state)) {
       DEBUG_printf("Scan already in progress, skipping\n");
        return false;
    }
    absolute_time_t scan_start_time = get_absolute_time();
    absolute_time_t scan_time = make_timeout_time_ms(5000);
    cyw43_wifi_scan_options_t scan_options = { 0 };
    int err = cyw43_wifi_scan(&cyw43_state, &scan_options, this, STANode::scan_result);
    if (err != 0) {
       DEBUG_printf("Failed to start scan: %d\n", err);
        return false;
    }
    DEBUG_printf("...");
    // Wait for scan to complete with timeout
    while (cyw43_wifi_scan_active(&cyw43_state)) {
        if (absolute_time_diff_us(scan_start_time, get_absolute_time()) > 5000000) {
           DEBUG_printf("Scan timeout\n");
            return false;
        }
        #if PICO_CYW43_ARCH_POLL
            cyw43_arch_poll();
            cyw43_arch_wait_for_work_until(scan_time);
        #else
            sleep_ms(100);
        #endif
    }
    DEBUG_printf("---");
    return true;
}
References DEBUG_printf, known_nodes, and scan_result().
Referenced by connect_to_network(), core1_entry(), and main().
scan_result()
int STANode::scan_result (void * env, const cyw43_ev_scan_result_t * result) static
{
    if (result == NULL) {
        return 0;
    }
    // copy the result
    cyw43_ev_scan_result_t* result_copy = static_cast<cyw43_ev_scan_result_t*>(malloc(sizeof(cyw43_ev_scan_result_t)));
    if (result_copy) {
        memcpy(result_copy, result, sizeof(cyw43_ev_scan_result_t));
    }
    STANode* self = static_cast<STANode*>(env);
    const char* ssid_str = reinterpret_cast<const char*>(result->ssid);
    const char* prefix = "GatorGrid_Node:";
    size_t prefix_len = strlen(prefix);
    //printf(ssid_str);
    //printf("\n");
    if (strncmp(ssid_str, prefix, prefix_len) == 0) {
        unsigned int id; // Changed to unsigned int for hexadecimal
        if (sscanf(ssid_str, "GatorGrid_Node:%x", &id) == 1) { // Changed format to %x for hexadecimal
            // Add to known nodes if not already present
            if (self->get_NodeID() == id) {
                //printf("Ignoring own AP node\n");
                goto free_mem;
            } else if (self->known_nodes.find(id) == self->known_nodes.end()) {
               DEBUG_printf("New node ID: 0x%x\n", id); // Changed format to 0x%x for hexadecimal output
               DEBUG_printf("New node ID: 0x%x, SSID: %s, Signal strength: %d dBm\n", id, (char*)&(result->ssid), result->rssi);
                self->known_nodes[id] = result_copy;
            } else {
                // Free if node is already known
                goto free_mem;
            }
        } else {
            // Free if parsing fails
            goto free_mem;
        }
    } else {
        // Free if SSID doesn't match prefix
        goto free_mem;
    }
    return 0;
free_mem:
    free(result_copy);
    return 0;
}
References DEBUG_printf, MeshNode::get_NodeID(), and known_nodes.
Referenced by scan_for_nodes().
send_data()
err_t STANode::send_data (uint32_t send_id, ssize_t len, uint8_t * buf)
{
    TCP_DATA_MSG msg(get_NodeID(), send_id);
    msg.add_message(buf, len);
    if (!send_tcp_data_blocking(msg.get_msg(), msg.get_len(), false))
        return -1;
    return 0;
}
References TCP_DATA_MSG::add_message(), TCP_DATA_MSG::get_len(), TCP_DATA_MSG::get_msg(), MeshNode::get_NodeID(), and send_tcp_data_blocking().
send_msg()
err_t STANode::send_msg (uint8_t * msg)
{
    //TCP_MESSAGE* tcp_msg = parseMessage(msg);
    size_t len = 0;
    uint32_t target_id = 0;
    tcp_pcb *target = nullptr;
    bool forward = false;
    uint8_t id = msg[1];
    switch (id) {
        case 0x00:  // Init message from STA -> thus new parent has been added
        {           // This message should probably never be received via serial
            // TCP_INIT_MESSAGE* initMsg = reinterpret_cast<TCP_INIT_MESSAGE*>(msg);
            // parent = initMsg->msg.source;
            TCP_INIT_MESSAGE initMsg;
            initMsg.set_msg(msg);
            return 0;
        }
        case 0x01: /* TCP_DATA_MSG */
        {
            TCP_DATA_MSG dataMsg;
            dataMsg.set_msg(msg);
            len = dataMsg.get_len();
            target_id = dataMsg.msg.dest;
            DUMP_BYTES(dataMsg.get_msg(), len);
            if (dataMsg.msg.source != get_NodeID()) forward = true;
            break;
        }
        case 0x02: /* TCP_DISCONNECT_MSG */
            // Sending this seems meaningless -> just update parent via STA
            //TCP_DISCONNECT_MSG* killMsg = reinterpret_cast<TCP_DISCONNECT_MSG*>(msg);
            //len = killMsg->get_len();
            //target_id = killMsg->msg.;
            break;
        case 0x03: /* TCP_UPDATE_MESSAGE */
        {
            DEBUG_printf("TCP_UPDATE_MESSAGE being sent");
            TCP_UPDATE_MESSAGE updateMsg;
            updateMsg.set_msg(msg);
            len = updateMsg.get_len();
            target_id = updateMsg.msg.dest;
            if (updateMsg.msg.source != get_NodeID()) {
                DEBUG_printf("Update message was passing through");
                forward = true;
            }
            break;
        }
        case 0x04: /* TCP_ACK_MESSAGE */
        {
            TCP_ACK_MESSAGE ackMsg;
            ackMsg.set_msg(msg);
            len = ackMsg.get_len();
            target_id = ackMsg.msg.dest;
            if (ackMsg.msg.source != get_NodeID()) forward = true;
            break;
        }
        case 0x05: /* TCP_NAK_MESSAGE */
        {
            TCP_NAK_MESSAGE nakMsg;
            nakMsg.set_msg(msg);
            len = nakMsg.get_len();
            target_id = nakMsg.msg.dest;
            if (nakMsg.msg.source != get_NodeID()) forward = true;
            break;
        }
        case 0x06: /* TCP_FORCE_UPDATE_MESSAGE */
        {
            TCP_FORCE_UPDATE_MESSAGE fUpdateMsg;
            fUpdateMsg.set_msg(msg);
            len = fUpdateMsg.get_len();
            target_id = fUpdateMsg.msg.dest;
            forward = true;
            break;
        }
        default:
        {
            return -1;
        }
    }
    DUMP_BYTES(msg, len);
    uint32_t path_parent = 0;
    if (!tree.find_path_parent(target_id, &path_parent)) {
        DEBUG_printf(forward ? "Forwarding message" : "Expecting ACK");
        if (!send_tcp_data_blocking(msg, len, forward)) {
            ERROR_printf("send_tcp_data_blocking failed");
            return -1;
        }
    } else {
        SERIAL_DATA_MESSAGE serialMsg;
        serialMsg.add_message(msg, len);
        uart.sendMessage((char*)serialMsg.get_msg());
    }
    DEBUG_printf("Message successfully sent");
    return 0;
}
References SERIAL_DATA_MESSAGE::add_message(), DEBUG_printf, DUMP_BYTES, ERROR_printf, ChildrenTree::find_path_parent(), TCP_DATA_MSG::get_len(), TCP_UPDATE_MESSAGE::get_len(), TCP_ACK_MESSAGE::get_len(), TCP_NAK_MESSAGE::get_len(), TCP_FORCE_UPDATE_MESSAGE::get_len(), TCP_DATA_MSG::get_msg(), SERIAL_DATA_MESSAGE::get_msg(), MeshNode::get_NodeID(), TCP_DATA_MSG::msg, TCP_UPDATE_MESSAGE::msg, TCP_ACK_MESSAGE::msg, TCP_NAK_MESSAGE::msg, TCP_FORCE_UPDATE_MESSAGE::msg, send_tcp_data_blocking(), PicoUART::sendMessage(), TCP_INIT_MESSAGE::set_msg(), TCP_DATA_MSG::set_msg(), TCP_UPDATE_MESSAGE::set_msg(), TCP_ACK_MESSAGE::set_msg(), TCP_NAK_MESSAGE::set_msg(), TCP_FORCE_UPDATE_MESSAGE::set_msg(), tree, and uart.
Referenced by handle_incoming_data(), handle_serial_message(), main(), and update_network().
send_tcp_data()
bool STANode::send_tcp_data (uint8_t * data, uint32_t size, bool forward)
{
    // uint8_t buffer[size] = {};
    // if (size > BUF_SIZE) { size = size; }
    // memcpy(buffer, data, size);
    bool flag = false;
    // while(state->tcp_pcb->snd_buf != 0) {
    //  DEBUG_printf("tcp buffer has %d bytes in it\n", state->tcp_pcb->snd_buf);
    // }
    if (!forward) {
        while(state->waiting_for_ack); //{sleep_ms(5);}
    }
    //sleep_ms(10);
    cyw43_arch_lwip_begin();
    //printf("Space used in the buffer %d\n", tcp_sndbuf(state->tcp_pcb));
    // while (tcp_write(state->tcp_pcb, (void*)buffer, BUF_SIZE, TCP_WRITE_FLAG_COPY) == -1) {
    //    DEBUG_printf("attempting to write\n");
    //     sleep_ms(2);
    // }
    // Not getting an ack message back for some reason
    //sleep_ms(125);
    DEBUG_printf("Before tpc_write\n");
    err_t err = tcp_write(state->tcp_pcb, (void*)data, size, TCP_WRITE_FLAG_COPY);
    DEBUG_printf("After tpc_write\n");
    err_t err2 = tcp_output(state->tcp_pcb);
    DEBUG_printf("After tpc_output\n");
    if (err != ERR_OK) {
       DEBUG_printf("Message failed to write\n");
       DEBUG_printf("ERR: %d\n", err);
        flag = true;
    }
    if (err2 != ERR_OK) {
       DEBUG_printf("Message failed to be sent\n");
        flag = true;
    }
    cyw43_arch_lwip_end();
    if (flag)
      return false;
    DEBUG_printf("SENDING BYTES BELOW: \n");
    state->waiting_for_ack = !forward;
    DUMP_BYTES(data, size);
    return true;
}
References DEBUG_printf, DUMP_BYTES, state, TCP_CLIENT_T_::tcp_pcb, and TCP_CLIENT_T_::waiting_for_ack.
Referenced by handle_incoming_data(), and main().
send_tcp_data_blocking()
bool STANode::send_tcp_data_blocking (uint8_t * data, uint32_t size, bool forward)
Will wait until availble to send tcp, then will wait for an ACK response before releasing.
Parameters
data
size
forward
Returns
true - message successfully sent
false - message failed to send
{
    bool flag = false;
    while(state->waiting_for_ack);
    cyw43_arch_lwip_begin();
    DEBUG_printf("blocking before write/output\n");
    err_t err = tcp_write(state->tcp_pcb, (void*)data, size, TCP_WRITE_FLAG_COPY);
    err_t err2 = tcp_output(state->tcp_pcb);
    DEBUG_printf("blocking after write/output\n");
    if (err != ERR_OK) {
       DEBUG_printf("Message failed to write\n");
       DEBUG_printf("ERR: %d\n", err);
        flag = true;
    }
    if (err2 != ERR_OK) {
       DEBUG_printf("Message failed to be sent\n");
        flag = true;
    }
    cyw43_arch_lwip_end();
    if (flag) {
        DEBUG_printf("Some error in write/output\n");
      return false;
    }
    DEBUG_printf("SENDING BYTES BELOW: \n");
    DUMP_BYTES(data, size);
    state->waiting_for_ack = !forward;
    int count = 0;
    while(state->waiting_for_ack)
    {
        sleep_ms(2);
        printf(".");
        count++;
        if(count == 1000) {
            state->waiting_for_ack = false;
            DEBUG_printf("\nTimeout\n");
            return false;
        }
    }
    if (state->got_nak) {
        DEBUG_printf("Got NAK, returning false\n");
        return false;
    }
    return true;
}
References DEBUG_printf, DUMP_BYTES, TCP_CLIENT_T_::got_nak, state, TCP_CLIENT_T_::tcp_pcb, and TCP_CLIENT_T_::waiting_for_ack.
Referenced by send_data(), send_msg(), and tcp_init().
start_sta_mode()
bool STANode::start_sta_mode ()
{
    cyw43_arch_enable_sta_mode();
    DEBUG_printf("Starting STA mode\n");
    // tell AP that it has fully started
    uint8_t buf[300];
    *(uint32_t*)buf = this->get_NodeID();
    uart.sendMessage((char*)buf);
    return true; // ggwp
}
References DEBUG_printf, MeshNode::get_NodeID(), PicoUART::sendMessage(), and uart.
Referenced by core1_entry(), and main().
tcp_init()
bool STANode::tcp_init ()
                       {
    state = tcp_client_init();
    if (!state) {
       DEBUG_printf("Unable to initialize tcp client state\n");
        return false;
    }
   DEBUG_printf("Initialized tcp client\n");
    state->got_nak = false;
    if (!tcp_client_open(this)) {
       DEBUG_printf("Failed to open client\n");
        tcp_result(state, -1);
        return false;
    }
   DEBUG_printf("Opened tcp client connection\n");
    //uint8_t buffer[BUF_SIZE] = {};
    //create_join_message(BUF_SIZE, buffer, this);
    TCP_INIT_MESSAGE init_msg(get_NodeID(), parent);
    return send_tcp_data_blocking(init_msg.get_msg(), init_msg.get_len(), false);
}
References DEBUG_printf, TCP_INIT_MESSAGE::get_len(), TCP_INIT_MESSAGE::get_msg(), MeshNode::get_NodeID(), TCP_CLIENT_T_::got_nak, parent, send_tcp_data_blocking(), state, tcp_client_init(), tcp_client_open(), and tcp_result().
Referenced by main().
update_network()
err_t STANode::update_network ()
{
    uint32_t children_ids[4] = {0};
    uint8_t children_count = 0;
    tree.get_children(get_NodeID(), children_ids, children_count);
    for (int i = 0; i < children_count; i++) {
        TCP_FORCE_UPDATE_MESSAGE forceUpdateMsg(children_ids[i], get_NodeID());
        send_msg(forceUpdateMsg.get_msg());
    }
    return 0;
}
References ChildrenTree::get_children(), TCP_FORCE_UPDATE_MESSAGE::get_msg(), MeshNode::get_NodeID(), send_msg(), and tree.
Member Data Documentation
AP_CONNECTED_IP
std::string STANode::AP_CONNECTED_IP
known_nodes
std::map<int, cyw43_ev_scan_result_t*> STANode::known_nodes
Referenced by connect_to_network(), connect_to_node(), main(), scan_for_nodes(), scan_result(), STANode(), and ~STANode().
parent
uint32_t STANode::parent
Referenced by connect_to_network(), connect_to_node(), handle_serial_message(), main(), STANode(), and tcp_init().
rb
RingBuffer STANode::rb
Referenced by handle_incoming_data(), and number_of_messages().
state
TCP_CLIENT_T* STANode::state
Referenced by handle_incoming_data(), send_tcp_data(), send_tcp_data_blocking(), tcp_client_close(), tcp_client_connected(), tcp_client_open(), tcp_client_recv(), tcp_client_sent(), tcp_init(), and tcp_result().
tree
ChildrenTree STANode::tree
Referenced by handle_incoming_data(), handle_serial_message(), init_sta_mode(), main(), send_msg(), and update_network().
uart
PicoUART STANode::uart
Referenced by handle_incoming_data(), init_sta_mode(), main(), poll(), send_msg(), STANode(), and start_sta_mode().
The documentation for this class was generated from the following files:
libraries/MeshNode/MeshNode.hpp
libraries/MeshNode/MeshNodeSTA.cpp
libraries/MeshNode/STAMessageHandling.cpp