GatorGrid: Dht11 Class Reference
Dht11 Class Reference
DHT11 Sensor Class.
#include <dht11-pico.h>
Public Member Functions
Dht11 (uint pin)
Dht11 class constructor. Initializes GPIO and waits for the sensor to stablize.
~Dht11 ()
Dht11 class destructor. De-initialize GPIO.
double readT (void)
Read and retrieve the temperature value from the DHT11 sensor.
double readRH (void)
Read and retrieve the humidity value from the DHT11 sensor.
void readRHT (double *temperature, double *rel_humidity)
Read both temperature and humidity values from the DHT11 sensor.
Private Member Functions
long long read (void)
Private method to read raw data from the DHT11 sensor.
Private Attributes
uint gpioPin
GPIO pin connected to the DHT11 sensor.
Detailed Description
DHT11 Sensor Class.
This class provides methods to initialize, read, and retrieve temperature and humidity values from the DHT11 sensor.
Constructor & Destructor Documentation
Dht11()
Dht11::Dht11 (uint pin)
Dht11 class constructor. Initializes GPIO and waits for the sensor to stablize.
Parameters
pin GPIO pin number connected to the DHT11 sensor.
                    {
    gpioPin=pin;
    gpio_init(pin);
    sleep_ms(1000);
}
References gpioPin.
~Dht11()
Dht11::~Dht11 ()
Dht11 class destructor. De-initialize GPIO.
             {
    gpio_deinit(gpioPin);
}
References gpioPin.
Member Function Documentation
read()
long long Dht11::read (void) private
Private method to read raw data from the DHT11 sensor.
Returns
Raw data read from the DHT11 sensor.
This method reads the raw data from the DHT11 sensor by sending and receiving pulses to determine the temperature and humidity values.
                     {
    int count=0;
    long long raw=0;
    gpio_set_dir(gpioPin, GPIO_OUT);
    gpio_put(gpioPin,0);
    sleep_ms(20);
    gpio_set_dir(gpioPin, GPIO_IN);
    while(gpio_get(gpioPin)==1){
        count++;
        sleep_us(5);
        if(count==POLLING_LIMIT){
            return TRANSMISSION_ERROR;
        }
    }
    count=0;
    while(gpio_get(gpioPin)==0){
        count++;
        sleep_us(5);
        if(count==POLLING_LIMIT){
            return TRANSMISSION_ERROR;
        }
    }
    count=0;
    while(gpio_get(gpioPin)==1){
        count++;
        sleep_us(5);
        if(count==POLLING_LIMIT){
            return TRANSMISSION_ERROR;
        }
    }
    //transmission start
    for(int i=0;i<40;i++){
        count=0;
        //~50us
        while(gpio_get(gpioPin)==0){
            sleep_us(5);
        }
        //bit 0 or 1
        while(gpio_get(gpioPin)==1){
            sleep_us(5);
            count++;
        }
        if(count>=THRESHOLD){
            raw|=1;
        }
        raw=raw<<1;
    }
    //check if raw data is valid
    if(
        ((raw & RH_INT_MASK)>>32)   +
        ((raw & RH_DEC_MASK)>>24)   +
        ((raw & TEMP_INT_MASK)>>16) +
        ((raw & TEMP_DEC_MASK)>>8)  -
        ((raw & CHECKSUM_MASK))     > 1
        ){
        return TRANSMISSION_ERROR;
    }
    return raw;
}
References CHECKSUM_MASK, gpioPin, POLLING_LIMIT, RH_DEC_MASK, RH_INT_MASK, TEMP_DEC_MASK, TEMP_INT_MASK, THRESHOLD, and TRANSMISSION_ERROR.
Referenced by readRH(), readRHT(), and readT().
readRH()
double Dht11::readRH (void)
Read and retrieve the humidity value from the DHT11 sensor.
Returns
Humidity value read from the DHT11 sensor, or TRANSMISSION_ERROR if there is a transmission error.
This method reads the humidity value from the DHT11 sensor and returns it as a double value. If there is a transmission error, TRANSMISSION_ERROR is returned.
                    {
    long long raw=read();
    if(raw==TRANSMISSION_ERROR){
        return TRANSMISSION_ERROR;
    }
    int rh_int    =    (raw & RH_INT_MASK)>>32;
    uint rh_dec   =    (raw & RH_DEC_MASK)>>24;
    double rh     =    rh_int + 0.1*rh_dec;
    return rh;
}
References read(), RH_DEC_MASK, RH_INT_MASK, and TRANSMISSION_ERROR.
readRHT()
void Dht11::readRHT (double * temperature, double * rel_humidity)
Read both temperature and humidity values from the DHT11 sensor.
Parameters
temperature Pointer to a double variable to store the temperature value.
humidity Pointer to a double variable to store the humidity value.
This method reads both the temperature and humidity values from the DHT11 sensor and stores them in the provided variables. If there is a transmission error, the values are set to TRANSMISSION_ERROR.
{
    long long raw=read();
    if(raw==TRANSMISSION_ERROR){
        *temp= *rh = TRANSMISSION_ERROR;
        return;
    }
    int temp_int    =    (raw & TEMP_INT_MASK)>>16;
    uint temp_dec   =    (raw & TEMP_DEC_MASK)>>8;
    int rh_int      =    (raw & RH_INT_MASK)>>32;
    uint rh_dec     =    (raw & RH_DEC_MASK)>>24;
    *temp           =    temp_int + 0.1*temp_dec;
    *rh             =    rh_int + 0.1*rh_dec;
}
References read(), RH_DEC_MASK, RH_INT_MASK, TEMP_DEC_MASK, TEMP_INT_MASK, and TRANSMISSION_ERROR.
readT()
double Dht11::readT (void)
Read and retrieve the temperature value from the DHT11 sensor.
Returns
Temperature value read from the DHT11 sensor, or TRANSMISSION_ERROR if there is a transmission error.
This method reads the temperature value from the DHT11 sensor and returns it as a double value. If there is a transmission error, TRANSMISSION_ERROR is returned.
                   {
    long long raw=read();
    if(raw==TRANSMISSION_ERROR){
        return TRANSMISSION_ERROR;
    }
    int temp_int    =    (raw & TEMP_INT_MASK)>>16;
    uint temp_dec   =    (raw & TEMP_DEC_MASK)>>8;
    if(temp_int<0)
        temp_dec=-temp_dec;
    double temp     =    temp_int + 0.1*temp_dec;
    return temp;
}
References read(), TEMP_DEC_MASK, TEMP_INT_MASK, and TRANSMISSION_ERROR.
Member Data Documentation
gpioPin
uint Dht11::gpioPin private
GPIO pin connected to the DHT11 sensor.
Referenced by Dht11(), read(), and ~Dht11().
The documentation for this class was generated from the following files:
libraries/DHT11/dht11-pico.h
libraries/DHT11/dht11-pico.cpp