GatorGrid: MeshNode Class Reference
MeshNode Class Reference
#include <MeshNode.hpp>
Public Member Functions
MeshNode ()
virtual ~MeshNode ()
void set_NodeID (uint32_t ID)
uint32_t get_NodeID ()
void seed_rand ()
bool get_is_root ()
void set_is_root (bool status)
Public Attributes
bool is_root = false
Private Attributes
uint32_t NodeID
Constructor & Destructor Documentation
MeshNode()
MeshNode::MeshNode ()
                   {
    seed_rand();
    // set the NodeID variable
    set_NodeID(rand());
}
References seed_rand(), and set_NodeID().
~MeshNode()
MeshNode::~MeshNode () virtual
                   {
    NodeID = 0;
}
References NodeID.
Member Function Documentation
get_is_root()
bool MeshNode::get_is_root ()
{
    return is_root;
}
References is_root.
get_NodeID()
uint32_t MeshNode::get_NodeID ()
{
    return NodeID;
}
References NodeID.
Referenced by APNode::APNode(), APNode::get_node_id(), APNode::handle_incoming_data(), STANode::handle_incoming_data(), STANode::init_sta_mode(), main(), STANode::scan_result(), APNode::send_data(), STANode::send_data(), STANode::send_msg(), APNode::start_ap_mode(), STANode::start_sta_mode(), STANode::tcp_init(), and STANode::update_network().
seed_rand()
void MeshNode::seed_rand ()
{
    uint32_t random = 0x811c9dc5;
    uint8_t next_byte = 0;
    volatile uint32_t *rnd_reg = (uint32_t *)(ROSC_BASE + ROSC_RANDOMBIT_OFFSET);
    for (int i = 0; i < 16; i++) {
      for (int k = 0; k < 8; k++) {
        next_byte = (next_byte << 1) | (*rnd_reg & 1);
      }
      random ^= next_byte;
      random *= 0x01000193;
    }
    srand(random);
  }
Referenced by MeshNode().
set_is_root()
void MeshNode::set_is_root (bool status)
{
    is_root = status;
}
References is_root.
set_NodeID()
void MeshNode::set_NodeID (uint32_t ID)
{
    // Assign ID to NodeID
    NodeID = ID; // Random number between 1 and 10,000
}
References NodeID.
Referenced by APNode::APNode(), STANode::init_sta_mode(), MeshNode(), APNode::set_node_id(), and STANode::STANode().
Member Data Documentation
is_root
bool MeshNode::is_root = false
Referenced by get_is_root(), APNode::handle_incoming_data(), and set_is_root().
NodeID
uint32_t MeshNode::NodeID private
Referenced by get_NodeID(), set_NodeID(), and ~MeshNode().
The documentation for this class was generated from the following files:
libraries/MeshNode/MeshNode.hpp
libraries/MeshNode/MeshNodeAP.cpp