GatorGrid: SERIAL_DATA_MESSAGE Class Reference
SERIAL_DATA_MESSAGE Class Reference
#include <SerialMessages.hpp>
Public Member Functions
SERIAL_DATA_MESSAGE ()
void add_message (uint8_t *msg_i, uint8_t msg_len)
uint8_t * get_data ()
uint8_t * get_msg () override
uint16_t get_data_len ()
uint16_t get_len () override
void set_msg (void *msg) override
Public Member Functions inherited from SERIAL_MESSAGE
SERIAL_MESSAGE ()
~SERIAL_MESSAGE ()
virtual uint8_t * get_msg ()=0
virtual uint16_t get_len ()=0
virtual void set_msg (void *msg)=0
struct __attribute__ ((__packed__)) serial_node_add_msg_t
struct __attribute__ ((__packed__)) serial_node_remove_msg_t
struct __attribute__ ((__packed__)) serial_data_msg_t
struct __attribute__ ((__packed__)) serial_fatal_error_msg_t
Public Attributes
serial_data_msg_t msg = {0}
Public Attributes inherited from SERIAL_MESSAGE
serial_node_add_msg
serial_node_remove_msg
serial_data_msg
serial_fatal_error_msg
Additional Inherited Members
Protected Attributes inherited from SERIAL_MESSAGE
uint8_t priority
Constructor & Destructor Documentation
SERIAL_DATA_MESSAGE()
SERIAL_DATA_MESSAGE::SERIAL_DATA_MESSAGE () inline
                          : SERIAL_MESSAGE() {
        msg.msg_id = 0x02;
        msg.msg_len = 0; // size of network buffer packet
    }
References msg.
Member Function Documentation
add_message()
void SERIAL_DATA_MESSAGE::add_message (uint8_t * msg_i, uint8_t msg_len) inline
{
        memcpy(msg.msg, msg_i, msg_len > MAX_MESSAGE_LENGTH - 5 ? MAX_MESSAGE_LENGTH - 5 : msg_len);
        msg.msg_len = msg_len > MAX_MESSAGE_LENGTH - 5 ? MAX_MESSAGE_LENGTH - 5 : msg_len;
        msg.len = msg.msg_len + 5;
    }
References MAX_MESSAGE_LENGTH, and msg.
Referenced by APNode::handle_incoming_data(), STANode::handle_incoming_data(), and STANode::send_msg().
get_data()
uint8_t * SERIAL_DATA_MESSAGE::get_data () inline
{
        return reinterpret_cast<uint8_t*>(msg.msg);
    }
References msg.
Referenced by APNode::handle_serial_message(), and STANode::handle_serial_message().
get_data_len()
uint16_t SERIAL_DATA_MESSAGE::get_data_len () inline
{
        return msg.msg_len;
    }
References msg.
Referenced by STANode::handle_serial_message().
get_len()
uint16_t SERIAL_DATA_MESSAGE::get_len () inline override virtual
Implements SERIAL_MESSAGE.
{
        return msg.len;
    }
References msg.
get_msg()
uint8_t * SERIAL_DATA_MESSAGE::get_msg () inline override virtual
Implements SERIAL_MESSAGE.
{
        return reinterpret_cast<uint8_t*>(&msg);
    }
References msg.
Referenced by APNode::handle_incoming_data(), STANode::handle_incoming_data(), and STANode::send_msg().
set_msg()
void SERIAL_DATA_MESSAGE::set_msg (void * msg) inline override virtual
Implements SERIAL_MESSAGE.
{
        this->msg = *(reinterpret_cast<serial_data_msg_t*>(msg));
    }
References msg.
Referenced by APNode::handle_serial_message(), and STANode::handle_serial_message().
Member Data Documentation
msg
serial_data_msg_t SERIAL_DATA_MESSAGE::msg = {0}
Referenced by add_message(), get_data(), get_data_len(), get_len(), get_msg(), SERIAL_DATA_MESSAGE(), and set_msg().
The documentation for this class was generated from the following file:
libraries/SPI/SerialMessages.hpp