GatorGrid: TCP_DISCONNECT_MSG Class Reference
TCP_DISCONNECT_MSG Class Reference
#include <Messages.hpp>
Public Member Functions
TCP_DISCONNECT_MSG (uint32_t src_id)
void lost_node (uint32_t lost_node, uint8_t cause)
void add_children (uint8_t children_count, uint32_t *children)
uint8_t * get_msg () override
uint16_t get_len () override
void set_msg (void *msg) override
Public Member Functions inherited from TCP_MESSAGE
TCP_MESSAGE (uint8_t priority)
~TCP_MESSAGE ()
virtual uint8_t * get_msg ()=0
virtual uint16_t get_len ()=0
virtual void set_msg (void *msg)=0
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
Public Attributes
tcp_disconnect_msg_t msg = {0}
Public Attributes inherited from TCP_MESSAGE
tcp_init_msg_t
tcp_update_msg_t
tcp_data_msg_t
tcp_disconnect_msg_t
tcp_acknowledge_msg_t
tcp_failed_msg_t
tcp_force_update_msg_t
Additional Inherited Members
Protected Attributes inherited from TCP_MESSAGE
uint8_t priority
Constructor & Destructor Documentation
TCP_DISCONNECT_MSG()
TCP_DISCONNECT_MSG::TCP_DISCONNECT_MSG (uint32_t src_id) inline
                                        : TCP_MESSAGE(0xFF) {
        msg.priority = priority;
        msg.msg_id = 0x02;
        msg.source = src_id;
        msg.len = 30;
    }
References msg, and TCP_MESSAGE::priority.
Member Function Documentation
add_children()
void TCP_DISCONNECT_MSG::add_children (uint8_t children_count, uint32_t * children) inline
{
        msg.child_count = children_count;
        for (int i = 0; i < children_count; i++) {
            msg.children_IDs[i] = children[i];
        }
    }
References msg.
get_len()
uint16_t TCP_DISCONNECT_MSG::get_len () inline override virtual
Implements TCP_MESSAGE.
{
        return msg.len;
    }
References msg.
get_msg()
uint8_t * TCP_DISCONNECT_MSG::get_msg () inline override virtual
Implements TCP_MESSAGE.
{
        return reinterpret_cast<uint8_t*>(&msg);
    }
References msg.
lost_node()
void TCP_DISCONNECT_MSG::lost_node (uint32_t lost_node, uint8_t cause) inline
{
        msg.lost_node = lost_node;
        msg.cause = cause;
    }
References lost_node(), and msg.
Referenced by lost_node().
set_msg()
void TCP_DISCONNECT_MSG::set_msg (void * msg) inline override virtual
Implements TCP_MESSAGE.
{
        this->msg = *(reinterpret_cast<tcp_disconnect_msg_t*>(msg));
    }
References msg, and TCP_MESSAGE::tcp_disconnect_msg_t.
Referenced by parseMessage().
Member Data Documentation
msg
tcp_disconnect_msg_t TCP_DISCONNECT_MSG::msg = {0}
Referenced by add_children(), get_len(), get_msg(), lost_node(), set_msg(), and TCP_DISCONNECT_MSG().
The documentation for this class was generated from the following file:
libraries/MeshNode/Messages.hpp