GatorGrid: TCP_UPDATE_MESSAGE Class Reference
TCP_UPDATE_MESSAGE Class Reference
#include <Messages.hpp>
Public Member Functions
TCP_UPDATE_MESSAGE (uint32_t id, uint32_t dest)
TCP_UPDATE_MESSAGE ()
void add_children (uint8_t children_count, uint32_t *children)
uint32_t get_child (int index)
uint8_t * get_msg () override
uint16_t get_len () override
uint8_t get_child_count ()
void set_msg (void *msg) override
Public Member Functions inherited from TCP_MESSAGE
TCP_MESSAGE (uint8_t priority)
~TCP_MESSAGE ()
virtual uint8_t * get_msg ()=0
virtual uint16_t get_len ()=0
virtual void set_msg (void *msg)=0
struct __attribute__ ((__packed__)) tcp_init_msg_t
struct __attribute__ ((__packed__)) tcp_update_msg_t
struct __attribute__ ((__packed__)) tcp_data_msg_t
struct __attribute__ ((__packed__)) tcp_disconnect_msg_t
struct __attribute__ ((__packed__)) tcp_acknowledge_msg_t
struct __attribute__ ((__packed__)) tcp_failed_msg_t
struct __attribute__ ((__packed__)) tcp_force_update_msg_t
Public Attributes
tcp_update_msg msg = {0}
Public Attributes inherited from TCP_MESSAGE
tcp_init_msg
tcp_update_msg
tcp_data_msg
tcp_disconnect_msg
tcp_acknowledge_msg
tcp_failed_msg
tcp_force_update_msg
Additional Inherited Members
Protected Attributes inherited from TCP_MESSAGE
uint8_t priority
Constructor & Destructor Documentation
TCP_UPDATE_MESSAGE() [1/2]
TCP_UPDATE_MESSAGE::TCP_UPDATE_MESSAGE (uint32_t id, uint32_t dest) inline
                                                   : TCP_MESSAGE(0xFF) {
        msg.priority = priority;
        msg.msg_id = 0x03;
        msg.len = 29;
        msg.source = id;
        msg.dest = dest;
        msg.child_count = 0;
    }
References msg, and TCP_MESSAGE::priority.
TCP_UPDATE_MESSAGE() [2/2]
TCP_UPDATE_MESSAGE::TCP_UPDATE_MESSAGE () inline
: TCP_MESSAGE(0xFF) {}
Member Function Documentation
add_children()
void TCP_UPDATE_MESSAGE::add_children (uint8_t children_count, uint32_t * children) inline
{
        msg.child_count = children_count;
        for (int i = 0; i < children_count; i++) {
            msg.children_IDs[i] = children[i];
        }
    }
References msg.
Referenced by STANode::handle_serial_message().
get_child()
uint32_t TCP_UPDATE_MESSAGE::get_child (int index) inline
{
        return msg.children_IDs[index];
    }
References msg.
Referenced by APNode::handle_incoming_data().
get_child_count()
uint8_t TCP_UPDATE_MESSAGE::get_child_count () inline
{
        return msg.child_count;
    }
References msg.
Referenced by APNode::handle_incoming_data().
get_len()
uint16_t TCP_UPDATE_MESSAGE::get_len () inline override virtual
Implements TCP_MESSAGE.
{
        return msg.len;
    }
References msg.
Referenced by APNode::send_msg(), and STANode::send_msg().
get_msg()
uint8_t * TCP_UPDATE_MESSAGE::get_msg () inline override virtual
Implements TCP_MESSAGE.
{
        return reinterpret_cast<uint8_t*>(&msg);
    }
References msg.
Referenced by STANode::handle_serial_message(), and APNode::handle_transfering_data().
set_msg()
void TCP_UPDATE_MESSAGE::set_msg (void * msg) inline override virtual
Implements TCP_MESSAGE.
{
        this->msg = *(reinterpret_cast<tcp_update_msg*>(msg));
    }
References msg, and TCP_MESSAGE::tcp_update_msg.
Referenced by APNode::handle_incoming_data(), STANode::handle_incoming_data(), APNode::handle_transfering_data(), APNode::send_msg(), and STANode::send_msg().
Member Data Documentation
msg
tcp_update_msg TCP_UPDATE_MESSAGE::msg = {0}
Referenced by add_children(), get_child(), get_child_count(), get_len(), get_msg(), APNode::handle_incoming_data(), STANode::handle_incoming_data(), APNode::send_msg(), STANode::send_msg(), set_msg(), and TCP_UPDATE_MESSAGE().
The documentation for this class was generated from the following file:
libraries/MeshNode/Messages.hpp