GatorGrid: SERIAL_NODE_ADD_MESSAGE Class Reference
SERIAL_NODE_ADD_MESSAGE Class Reference
#include <SerialMessages.hpp>
Public Member Functions
SERIAL_NODE_ADD_MESSAGE (uint32_t parent, uint32_t child)
SERIAL_NODE_ADD_MESSAGE ()
uint16_t get_len () override
uint32_t get_parent ()
uint32_t get_child ()
void set_msg (void *msg) override
uint8_t * get_msg () override
Public Member Functions inherited from SERIAL_MESSAGE
SERIAL_MESSAGE ()
~SERIAL_MESSAGE ()
virtual uint8_t * get_msg ()=0
virtual uint16_t get_len ()=0
virtual void set_msg (void *msg)=0
struct __attribute__ ((__packed__)) serial_node_add_msg_t
struct __attribute__ ((__packed__)) serial_node_remove_msg_t
struct __attribute__ ((__packed__)) serial_data_msg_t
struct __attribute__ ((__packed__)) serial_fatal_error_msg_t
Public Attributes
serial_node_add_msg_t msg = {0}
Public Attributes inherited from SERIAL_MESSAGE
serial_node_add_msg
serial_node_remove_msg
serial_data_msg
serial_fatal_error_msg
Additional Inherited Members
Protected Attributes inherited from SERIAL_MESSAGE
uint8_t priority
Constructor & Destructor Documentation
SERIAL_NODE_ADD_MESSAGE() [1/2]
SERIAL_NODE_ADD_MESSAGE::SERIAL_NODE_ADD_MESSAGE (uint32_t parent, uint32_t child) inline
                                                             : SERIAL_MESSAGE() {
        msg.msg_id = 0x00;
        msg.len = 11;
        msg.child = child;
        msg.parent = parent;
    }
References msg.
SERIAL_NODE_ADD_MESSAGE() [2/2]
SERIAL_NODE_ADD_MESSAGE::SERIAL_NODE_ADD_MESSAGE () inline
: SERIAL_MESSAGE() {}
Member Function Documentation
get_child()
uint32_t SERIAL_NODE_ADD_MESSAGE::get_child () inline
{
        return msg.child;
    }
References msg.
get_len()
uint16_t SERIAL_NODE_ADD_MESSAGE::get_len () inline override virtual
Implements SERIAL_MESSAGE.
{
        return msg.len;
    }
References msg.
get_msg()
uint8_t * SERIAL_NODE_ADD_MESSAGE::get_msg () inline override virtual
Implements SERIAL_MESSAGE.
{
        return reinterpret_cast<uint8_t*>(&msg);
    }
References msg.
Referenced by APNode::handle_incoming_data().
get_parent()
uint32_t SERIAL_NODE_ADD_MESSAGE::get_parent () inline
{
        return msg.parent;
    }
References msg.
Referenced by APNode::handle_serial_message().
set_msg()
void SERIAL_NODE_ADD_MESSAGE::set_msg (void * msg) inline override virtual
Implements SERIAL_MESSAGE.
{
        this->msg = *(reinterpret_cast<serial_node_add_msg_t*>(msg));
    }
References msg.
Referenced by APNode::handle_serial_message(), and STANode::handle_serial_message().
Member Data Documentation
msg
serial_node_add_msg_t SERIAL_NODE_ADD_MESSAGE::msg = {0}
Referenced by get_child(), get_len(), get_msg(), get_parent(), STANode::handle_serial_message(), SERIAL_NODE_ADD_MESSAGE(), and set_msg().
The documentation for this class was generated from the following file:
libraries/SPI/SerialMessages.hpp