GatorGrid: TCP_FORCE_UPDATE_MESSAGE Class Reference
TCP_FORCE_UPDATE_MESSAGE Class Reference
#include <Messages.hpp>
Public Member Functions
TCP_FORCE_UPDATE_MESSAGE (uint32_t dest, uint32_t source)
TCP_FORCE_UPDATE_MESSAGE ()
uint8_t * get_msg () override
uint16_t get_len () override
void set_msg (void *msg) override
Public Member Functions inherited from TCP_MESSAGE
TCP_MESSAGE (uint8_t priority)
~TCP_MESSAGE ()
virtual uint8_t * get_msg ()=0
virtual uint16_t get_len ()=0
virtual void set_msg (void *msg)=0
struct __attribute__ ((__packed__)) tcp_init_msg_t
struct __attribute__ ((__packed__)) tcp_update_msg_t
struct __attribute__ ((__packed__)) tcp_data_msg_t
struct __attribute__ ((__packed__)) tcp_disconnect_msg_t
struct __attribute__ ((__packed__)) tcp_acknowledge_msg_t
struct __attribute__ ((__packed__)) tcp_failed_msg_t
struct __attribute__ ((__packed__)) tcp_force_update_msg_t
Public Attributes
tcp_force_update_msg msg = {0}
Public Attributes inherited from TCP_MESSAGE
tcp_init_msg
tcp_update_msg
tcp_data_msg
tcp_disconnect_msg
tcp_acknowledge_msg
tcp_failed_msg
tcp_force_update_msg
Additional Inherited Members
Protected Attributes inherited from TCP_MESSAGE
uint8_t priority
Constructor & Destructor Documentation
TCP_FORCE_UPDATE_MESSAGE() [1/2]
TCP_FORCE_UPDATE_MESSAGE::TCP_FORCE_UPDATE_MESSAGE (uint32_t dest, uint32_t source) inline
                                                             : TCP_MESSAGE(0xFF) {
        msg.dest = dest;
        msg.source = source;
        msg.priority = priority;
        msg.msg_id = 0xFF;
        msg.len = sizeof(tcp_force_update_msg);
    }
References msg, TCP_MESSAGE::priority, and TCP_MESSAGE::tcp_force_update_msg.
TCP_FORCE_UPDATE_MESSAGE() [2/2]
TCP_FORCE_UPDATE_MESSAGE::TCP_FORCE_UPDATE_MESSAGE () inline
: TCP_MESSAGE(0xFF) {}
Member Function Documentation
get_len()
uint16_t TCP_FORCE_UPDATE_MESSAGE::get_len () inline override virtual
Implements TCP_MESSAGE.
{
        return msg.len;
    }
References msg.
Referenced by APNode::send_msg(), and STANode::send_msg().
get_msg()
uint8_t * TCP_FORCE_UPDATE_MESSAGE::get_msg () inline override virtual
Implements TCP_MESSAGE.
{
        return reinterpret_cast<uint8_t*>(&msg);
    }
References msg.
Referenced by STANode::update_network().
set_msg()
void TCP_FORCE_UPDATE_MESSAGE::set_msg (void * msg) inline override virtual
Implements TCP_MESSAGE.
{
        this->msg = *(reinterpret_cast<tcp_force_update_msg*>(msg));
    }
References msg, and TCP_MESSAGE::tcp_force_update_msg.
Referenced by APNode::send_msg(), and STANode::send_msg().
Member Data Documentation
msg
tcp_force_update_msg TCP_FORCE_UPDATE_MESSAGE::msg = {0}
Referenced by get_len(), get_msg(), APNode::send_msg(), STANode::send_msg(), set_msg(), and TCP_FORCE_UPDATE_MESSAGE().
The documentation for this class was generated from the following file:
libraries/MeshNode/Messages.hpp