GatorGrid: PicoUART Class Reference
PicoUART Class Reference
#include <UART.hpp>
Public Member Functions
PicoUART ()
~PicoUART ()=default
bool picoUARTInit ()
bool BufferReady ()
bool picoUARTInterruptInit ()
int sendMessage (const char *message)
uint8_t * getReadBuffer ()
Static Public Member Functions
static void on_uart_rx ()
Private Attributes
SerialRingBuffer srb
bool toggle = true
Static Private Attributes
static PicoUART * instance = nullptr
static int dma_chan
Constructor & Destructor Documentation
PicoUART()
PicoUART::PicoUART ()
                   {
    // Empty constructor
}
~PicoUART()
PicoUART::~PicoUART () default
Member Function Documentation
BufferReady()
bool PicoUART::BufferReady ()
{
    if (instance->srb.num_of_messages() > 0) {
        return true;
    } else {
        return false;
    }
}
References instance, SerialRingBuffer::num_of_messages(), and srb.
Referenced by STANode::init_sta_mode(), main(), STANode::poll(), APNode::poll(), and APNode::start_ap_mode().
getReadBuffer()
uint8_t * PicoUART::getReadBuffer ()
{
    uint8_t *buffer = instance->srb.buffer_get();
    // if the ring buffer is empty and they call getReadBuffer stall because something has gone wrong
    if(buffer == nullptr) {
        while(1) {
            ERROR_printf("Fatal Error: read buffer empty\n");
        }
    }
    return buffer;
}
References SerialRingBuffer::buffer_get(), ERROR_printf, instance, and srb.
Referenced by STANode::init_sta_mode(), main(), STANode::poll(), APNode::poll(), and APNode::start_ap_mode().
on_uart_rx()
void PicoUART::on_uart_rx () static
{
    // DEBUG_printf("ISR Triggered\n");
    if (!instance) {
        DEBUG_printf("instance is nullptr\n");
        return;
    }
    // ISR thrown twice, so just have a toggle gate guard it
    if (instance->toggle == false) {
        instance->toggle = true;
        // DEBUG_printf("Toggle protection thrown\n");
        return;
    }
    instance->toggle = false;
    // DEBUG_printf("get hw successful\n");
    uint8_t *buffer = instance->srb.buffer_put();
    // DEBUG_printf("got ISR buffer\n");
    // Should the ring buffer ever be full stall the pico
    if(buffer == nullptr) {
        while(1) {
            ERROR_printf("Serial recieved messages faster then poll could digest them\n");
        }
    }
    while (uart_is_readable(UART_ID)) {
        uart_read_blocking(UART_ID, buffer, MAX_LEN);
    }
    // DEBUG_printf("%02X %02X %02X %02X %02X\n", buffer[0],buffer[1],buffer[2],buffer[3],buffer[4]);
    // only clear flag after ISR has ran
    uart_get_hw(UART_ID)->icr = UART_UARTICR_RXIC_BITS;
    return;
}
References SerialRingBuffer::buffer_put(), DEBUG_printf, ERROR_printf, instance, MAX_LEN, srb, toggle, and UART_ID.
Referenced by picoUARTInterruptInit().
picoUARTInit()
bool PicoUART::picoUARTInit ()
{
    instance = this;
    uart_init(UART_ID, BAUD_RATE);
    gpio_set_function(UART_TX_PIN, GPIO_FUNC_UART);
    gpio_set_function(UART_RX_PIN, GPIO_FUNC_UART);
    uart_set_format(UART_ID, DATA_BITS, STOP_BITS, PARITY);
    uart_set_hw_flow(UART_ID, false, false);
    uart_set_fifo_enabled(UART_ID, false);
    return true;
}
References BAUD_RATE, DATA_BITS, instance, PARITY, STOP_BITS, UART_ID, UART_RX_PIN, and UART_TX_PIN.
Referenced by APNode::APNode(), main(), and STANode::STANode().
picoUARTInterruptInit()
bool PicoUART::picoUARTInterruptInit ()
{
    instance = this;
    int UART_IRQ = (UART_ID == uart0) ? UART0_IRQ : UART1_IRQ;
    irq_set_exclusive_handler(UART_IRQ, this->on_uart_rx);
    irq_set_enabled(UART_IRQ, true);
    uart_set_fifo_enabled(UART_ID, true);
    uart_set_irq_enables(UART_ID, true, false);
    return true;
}
References instance, on_uart_rx(), and UART_ID.
Referenced by APNode::APNode(), main(), and STANode::STANode().
sendMessage()
int PicoUART::sendMessage (const char * message)
{
    DEBUG_printf("Sending message over serial");
    while (!uart_is_writable(UART_ID)) {
        tight_loop_contents();
    }
    // If UART FIFO has data in it then don't write yet to avoid collision
    while(uart_is_readable(UART_ID)) {
        tight_loop_contents();
    }
    //uart_set_irq_enables(UART_ID, false, false);
    uart_write_blocking(UART_ID, (uint8_t *)message, MAX_LEN);
    //uart_set_irq_enables(UART_ID, true, false);
    return 0;
}
References DEBUG_printf, MAX_LEN, and UART_ID.
Referenced by APNode::handle_incoming_data(), STANode::handle_incoming_data(), main(), STANode::send_msg(), APNode::start_ap_mode(), and STANode::start_sta_mode().
Member Data Documentation
dma_chan
int PicoUART::dma_chan static private
instance
PicoUART * PicoUART::instance = nullptr static private
Referenced by BufferReady(), getReadBuffer(), on_uart_rx(), picoUARTInit(), and picoUARTInterruptInit().
srb
SerialRingBuffer PicoUART::srb private
Referenced by BufferReady(), getReadBuffer(), and on_uart_rx().
toggle
bool PicoUART::toggle = true private
Referenced by on_uart_rx().
The documentation for this class was generated from the following files:
libraries/UART/UART.hpp
libraries/UART/UART.cpp