GatorGrid: libraries/dhcpserver/dhcpserver.h File Reference
dhcpserver.h File Reference
#include "lwip/ip_addr.h"
Classes
struct _dhcp_server_lease_t
struct _dhcp_server_t
Macros
#define DHCPS_BASE_IP (16)
#define DHCPS_MAX_IP (8)
Typedefs
typedef struct _dhcp_server_lease_t dhcp_server_lease_t
typedef struct _dhcp_server_t dhcp_server_t
Functions
void dhcp_server_init (dhcp_server_t *d, ip_addr_t *ip, ip_addr_t *nm)
void dhcp_server_deinit (dhcp_server_t *d)
Macro Definition Documentation
DHCPS_BASE_IP
#define DHCPS_BASE_IP (16)
DHCPS_MAX_IP
#define DHCPS_MAX_IP (8)
Typedef Documentation
dhcp_server_lease_t
typedef struct _dhcp_server_lease_t dhcp_server_lease_t
dhcp_server_t
typedef struct _dhcp_server_t dhcp_server_t
Function Documentation
dhcp_server_deinit()
void dhcp_server_deinit (dhcp_server_t * d)
{
    dhcp_socket_free(&d->udp);
}
References dhcp_socket_free(), and _dhcp_server_t::udp.
dhcp_server_init()
void dhcp_server_init (dhcp_server_t * d, ip_addr_t * ip, ip_addr_t * nm)
{
    ip_addr_copy(d->ip, *ip);
    ip_addr_copy(d->nm, *nm);
    memset(d->lease, 0, sizeof(d->lease));
    if (dhcp_socket_new_dgram(&d->udp, d, dhcp_server_process) != 0) {
        return;
    }
    dhcp_socket_bind(&d->udp, PORT_DHCP_SERVER);
}
References dhcp_server_process(), dhcp_socket_bind(), dhcp_socket_new_dgram(), _dhcp_server_t::ip, _dhcp_server_t::lease, _dhcp_server_t::nm, PORT_DHCP_SERVER, and _dhcp_server_t::udp.
Referenced by APNode::start_ap_mode().