GatorGrid: libraries/dhcpserver/dhcpserver.c File Reference
dhcpserver.c File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include "cyw43_config.h"
#include "dhcpserver.h"
#include "lwip/udp.h"
Classes
struct dhcp_msg_t
Macros
#define DHCPDISCOVER (1)
#define DHCPOFFER (2)
#define DHCPREQUEST (3)
#define DHCPDECLINE (4)
#define DHCPACK (5)
#define DHCPNACK (6)
#define DHCPRELEASE (7)
#define DHCPINFORM (8)
#define DHCP_OPT_PAD (0)
#define DHCP_OPT_SUBNET_MASK (1)
#define DHCP_OPT_ROUTER (3)
#define DHCP_OPT_DNS (6)
#define DHCP_OPT_HOST_NAME (12)
#define DHCP_OPT_REQUESTED_IP (50)
#define DHCP_OPT_IP_LEASE_TIME (51)
#define DHCP_OPT_MSG_TYPE (53)
#define DHCP_OPT_SERVER_ID (54)
#define DHCP_OPT_PARAM_REQUEST_LIST (55)
#define DHCP_OPT_MAX_MSG_SIZE (57)
#define DHCP_OPT_VENDOR_CLASS_ID (60)
#define DHCP_OPT_CLIENT_ID (61)
#define DHCP_OPT_END (255)
#define PORT_DHCP_SERVER (67)
#define PORT_DHCP_CLIENT (68)
#define DEFAULT_LEASE_TIME_S (24 * 60 * 60)
#define MAC_LEN (6)
#define MAKE_IP4(a, b, c, d) ((a) << 24 | (b) << 16 | (c) << 8 | (d))
#define DHCP_MIN_SIZE (240 + 3)
Functions
static int dhcp_socket_new_dgram (struct udp_pcb **udp, void *cb_data, udp_recv_fn cb_udp_recv)
static void dhcp_socket_free (struct udp_pcb **udp)
static int dhcp_socket_bind (struct udp_pcb **udp, uint16_t port)
static int dhcp_socket_sendto (struct udp_pcb **udp, struct netif *nif, const void *buf, size_t len, uint32_t ip, uint16_t port)
static uint8_t * opt_find (uint8_t *opt, uint8_t cmd)
static void opt_write_n (uint8_t **opt, uint8_t cmd, size_t n, const void *data)
static void opt_write_u8 (uint8_t **opt, uint8_t cmd, uint8_t val)
static void opt_write_u32 (uint8_t **opt, uint8_t cmd, uint32_t val)
static void dhcp_server_process (void *arg, struct udp_pcb *upcb, struct pbuf *p, const ip_addr_t *src_addr, u16_t src_port)
void dhcp_server_init (dhcp_server_t *d, ip_addr_t *ip, ip_addr_t *nm)
void dhcp_server_deinit (dhcp_server_t *d)
Macro Definition Documentation
DEFAULT_LEASE_TIME_S
#define DEFAULT_LEASE_TIME_S (24 * 60 * 60)
DHCP_MIN_SIZE
#define DHCP_MIN_SIZE (240 + 3)
DHCP_OPT_CLIENT_ID
#define DHCP_OPT_CLIENT_ID (61)
DHCP_OPT_DNS
#define DHCP_OPT_DNS (6)
DHCP_OPT_END
#define DHCP_OPT_END (255)
DHCP_OPT_HOST_NAME
#define DHCP_OPT_HOST_NAME (12)
DHCP_OPT_IP_LEASE_TIME
#define DHCP_OPT_IP_LEASE_TIME (51)
DHCP_OPT_MAX_MSG_SIZE
#define DHCP_OPT_MAX_MSG_SIZE (57)
DHCP_OPT_MSG_TYPE
#define DHCP_OPT_MSG_TYPE (53)
DHCP_OPT_PAD
#define DHCP_OPT_PAD (0)
DHCP_OPT_PARAM_REQUEST_LIST
#define DHCP_OPT_PARAM_REQUEST_LIST (55)
DHCP_OPT_REQUESTED_IP
#define DHCP_OPT_REQUESTED_IP (50)
DHCP_OPT_ROUTER
#define DHCP_OPT_ROUTER (3)
DHCP_OPT_SERVER_ID
#define DHCP_OPT_SERVER_ID (54)
DHCP_OPT_SUBNET_MASK
#define DHCP_OPT_SUBNET_MASK (1)
DHCP_OPT_VENDOR_CLASS_ID
#define DHCP_OPT_VENDOR_CLASS_ID (60)
DHCPACK
#define DHCPACK (5)
DHCPDECLINE
#define DHCPDECLINE (4)
DHCPDISCOVER
#define DHCPDISCOVER (1)
DHCPINFORM
#define DHCPINFORM (8)
DHCPNACK
#define DHCPNACK (6)
DHCPOFFER
#define DHCPOFFER (2)
DHCPRELEASE
#define DHCPRELEASE (7)
DHCPREQUEST
#define DHCPREQUEST (3)
MAC_LEN
#define MAC_LEN (6)
MAKE_IP4
#define MAKE_IP4 (a, b, c, d) ((a) << 24 | (b) << 16 | (c) << 8 | (d))
PORT_DHCP_CLIENT
#define PORT_DHCP_CLIENT (68)
PORT_DHCP_SERVER
#define PORT_DHCP_SERVER (67)
Function Documentation
dhcp_server_deinit()
void dhcp_server_deinit (dhcp_server_t * d)
{
    dhcp_socket_free(&d->udp);
}
References dhcp_socket_free(), and _dhcp_server_t::udp.
dhcp_server_init()
void dhcp_server_init (dhcp_server_t * d, ip_addr_t * ip, ip_addr_t * nm)
{
    ip_addr_copy(d->ip, *ip);
    ip_addr_copy(d->nm, *nm);
    memset(d->lease, 0, sizeof(d->lease));
    if (dhcp_socket_new_dgram(&d->udp, d, dhcp_server_process) != 0) {
        return;
    }
    dhcp_socket_bind(&d->udp, PORT_DHCP_SERVER);
}
References dhcp_server_process(), dhcp_socket_bind(), dhcp_socket_new_dgram(), _dhcp_server_t::ip, _dhcp_server_t::lease, _dhcp_server_t::nm, PORT_DHCP_SERVER, and _dhcp_server_t::udp.
Referenced by APNode::start_ap_mode().
dhcp_server_process()
static void dhcp_server_process (void * arg, struct udp_pcb * upcb, struct pbuf * p, const ip_addr_t * src_addr, u16_t src_port) static
{
    dhcp_server_t *d = arg;
    (void)upcb;
    (void)src_addr;
    (void)src_port;
    // This is around 548 bytes
    dhcp_msg_t dhcp_msg;
    #define DHCP_MIN_SIZE (240 + 3)
    if (p->tot_len < DHCP_MIN_SIZE) {
        goto ignore_request;
    }
    size_t len = pbuf_copy_partial(p, &dhcp_msg, sizeof(dhcp_msg), 0);
    if (len < DHCP_MIN_SIZE) {
        goto ignore_request;
    }
    dhcp_msg.op = DHCPOFFER;
    memcpy(&dhcp_msg.yiaddr, &ip4_addr_get_u32(ip_2_ip4(&d->ip)), 4);
    uint8_t *opt = (uint8_t *)&dhcp_msg.options;
    opt += 4; // assume magic cookie: 99, 130, 83, 99
    uint8_t *msgtype = opt_find(opt, DHCP_OPT_MSG_TYPE);
    if (msgtype == NULL) {
        // A DHCP package without MSG_TYPE?
        goto ignore_request;
    }
    switch (msgtype[2]) {
        case DHCPDISCOVER: {
            int yi = DHCPS_MAX_IP;
            for (int i = 0; i < DHCPS_MAX_IP; ++i) {
                if (memcmp(d->lease[i].mac, dhcp_msg.chaddr, MAC_LEN) == 0) {
                    // MAC match, use this IP address
                    yi = i;
                    break;
                }
                if (yi == DHCPS_MAX_IP) {
                    // Look for a free IP address
                    if (memcmp(d->lease[i].mac, "\x00\x00\x00\x00\x00\x00", MAC_LEN) == 0) {
                        // IP available
                        yi = i;
                    }
                    uint32_t expiry = d->lease[i].expiry << 16 | 0xffff;
                    if ((int32_t)(expiry - cyw43_hal_ticks_ms()) < 0) {
                        // IP expired, reuse it
                        memset(d->lease[i].mac, 0, MAC_LEN);
                        yi = i;
                    }
                }
            }
            if (yi == DHCPS_MAX_IP) {
                // No more IP addresses left
                goto ignore_request;
            }
            dhcp_msg.yiaddr[3] = DHCPS_BASE_IP + yi;
            opt_write_u8(&opt, DHCP_OPT_MSG_TYPE, DHCPOFFER);
            break;
        }
        case DHCPREQUEST: {
            uint8_t *o = opt_find(opt, DHCP_OPT_REQUESTED_IP);
            if (o == NULL) {
                // Should be NACK
                goto ignore_request;
            }
            if (memcmp(o + 2, &ip4_addr_get_u32(ip_2_ip4(&d->ip)), 3) != 0) {
                // Should be NACK
                goto ignore_request;
            }
            uint8_t yi = o[5] - DHCPS_BASE_IP;
            if (yi >= DHCPS_MAX_IP) {
                // Should be NACK
                goto ignore_request;
            }
            if (memcmp(d->lease[yi].mac, dhcp_msg.chaddr, MAC_LEN) == 0) {
                // MAC match, ok to use this IP address
            } else if (memcmp(d->lease[yi].mac, "\x00\x00\x00\x00\x00\x00", MAC_LEN) == 0) {
                // IP unused, ok to use this IP address
                memcpy(d->lease[yi].mac, dhcp_msg.chaddr, MAC_LEN);
            } else {
                // IP already in use
                // Should be NACK
                goto ignore_request;
            }
            d->lease[yi].expiry = (cyw43_hal_ticks_ms() + DEFAULT_LEASE_TIME_S * 1000) >> 16;
            dhcp_msg.yiaddr[3] = DHCPS_BASE_IP + yi;
            opt_write_u8(&opt, DHCP_OPT_MSG_TYPE, DHCPACK);
            printf("DHCPS: client connected: MAC=%02x:%02x:%02x:%02x:%02x:%02x IP=%u.%u.%u.%u\n",
                dhcp_msg.chaddr[0], dhcp_msg.chaddr[1], dhcp_msg.chaddr[2], dhcp_msg.chaddr[3], dhcp_msg.chaddr[4], dhcp_msg.chaddr[5],
                dhcp_msg.yiaddr[0], dhcp_msg.yiaddr[1], dhcp_msg.yiaddr[2], dhcp_msg.yiaddr[3]);
            break;
        }
        default:
            goto ignore_request;
    }
    opt_write_n(&opt, DHCP_OPT_SERVER_ID, 4, &ip4_addr_get_u32(ip_2_ip4(&d->ip)));
    opt_write_n(&opt, DHCP_OPT_SUBNET_MASK, 4, &ip4_addr_get_u32(ip_2_ip4(&d->nm)));
    opt_write_n(&opt, DHCP_OPT_ROUTER, 4, &ip4_addr_get_u32(ip_2_ip4(&d->ip))); // aka gateway; can have multiple addresses
    opt_write_n(&opt, DHCP_OPT_DNS, 4, &ip4_addr_get_u32(ip_2_ip4(&d->ip))); // this server is the dns
    opt_write_u32(&opt, DHCP_OPT_IP_LEASE_TIME, DEFAULT_LEASE_TIME_S);
    *opt++ = DHCP_OPT_END;
    struct netif *nif = ip_current_input_netif();
    dhcp_socket_sendto(&d->udp, nif, &dhcp_msg, opt - (uint8_t *)&dhcp_msg, 0xffffffff, PORT_DHCP_CLIENT);
ignore_request:
    pbuf_free(p);
}
References dhcp_msg_t::chaddr, DEFAULT_LEASE_TIME_S, DHCP_MIN_SIZE, DHCP_OPT_DNS, DHCP_OPT_END, DHCP_OPT_IP_LEASE_TIME, DHCP_OPT_MSG_TYPE, DHCP_OPT_REQUESTED_IP, DHCP_OPT_ROUTER, DHCP_OPT_SERVER_ID, DHCP_OPT_SUBNET_MASK, dhcp_socket_sendto(), DHCPACK, DHCPDISCOVER, DHCPOFFER, DHCPREQUEST, DHCPS_BASE_IP, DHCPS_MAX_IP, _dhcp_server_lease_t::expiry, _dhcp_server_t::ip, _dhcp_server_t::lease, _dhcp_server_lease_t::mac, MAC_LEN, _dhcp_server_t::nm, dhcp_msg_t::op, opt_find(), opt_write_n(), opt_write_u32(), opt_write_u8(), dhcp_msg_t::options, PORT_DHCP_CLIENT, _dhcp_server_t::udp, and dhcp_msg_t::yiaddr.
Referenced by dhcp_server_init().
dhcp_socket_bind()
static int dhcp_socket_bind (struct udp_pcb ** udp, uint16_t port) static
{
    // TODO convert lwIP errors to errno
    return udp_bind(*udp, IP_ANY_TYPE, port);
}
Referenced by dhcp_server_init().
dhcp_socket_free()
static void dhcp_socket_free (struct udp_pcb ** udp) static
{
    if (*udp != NULL) {
        udp_remove(*udp);
        *udp = NULL;
    }
}
Referenced by dhcp_server_deinit().
dhcp_socket_new_dgram()
static int dhcp_socket_new_dgram (struct udp_pcb ** udp, void * cb_data, udp_recv_fn cb_udp_recv) static
{
    // family is AF_INET
    // type is SOCK_DGRAM
    *udp = udp_new();
    if (*udp == NULL) {
        return -ENOMEM;
    }
    // Register callback
    udp_recv(*udp, cb_udp_recv, (void *)cb_data);
    return 0; // success
}
Referenced by dhcp_server_init().
dhcp_socket_sendto()
static int dhcp_socket_sendto (struct udp_pcb ** udp, struct netif * nif, const void * buf, size_t len, uint32_t ip, uint16_t port) static
{
    if (len > 0xffff) {
        len = 0xffff;
    }
    struct pbuf *p = pbuf_alloc(PBUF_TRANSPORT, len, PBUF_RAM);
    if (p == NULL) {
        return -ENOMEM;
    }
    memcpy(p->payload, buf, len);
    ip_addr_t dest;
    IP4_ADDR(ip_2_ip4(&dest), ip >> 24 & 0xff, ip >> 16 & 0xff, ip >> 8 & 0xff, ip & 0xff);
    err_t err;
    if (nif != NULL) {
        err = udp_sendto_if(*udp, p, &dest, port, nif);
    } else {
        err = udp_sendto(*udp, p, &dest, port);
    }
    pbuf_free(p);
    if (err != ERR_OK) {
        return err;
    }
    return len;
}
Referenced by dhcp_server_process().
opt_find()
static uint8_t * opt_find (uint8_t * opt, uint8_t cmd) static
{
    for (int i = 0; i < 308 && opt[i] != DHCP_OPT_END;) {
        if (opt[i] == cmd) {
            return &opt[i];
        }
        i += 2 + opt[i + 1];
    }
    return NULL;
}
References DHCP_OPT_END.
Referenced by dhcp_server_process().
opt_write_n()
static void opt_write_n (uint8_t ** opt, uint8_t cmd, size_t n, const void * data) static
{
    uint8_t *o = *opt;
    *o++ = cmd;
    *o++ = n;
    memcpy(o, data, n);
    *opt = o + n;
}
Referenced by dhcp_server_process().
opt_write_u32()
static void opt_write_u32 (uint8_t ** opt, uint8_t cmd, uint32_t val) static
{
    uint8_t *o = *opt;
    *o++ = cmd;
    *o++ = 4;
    *o++ = val >> 24;
    *o++ = val >> 16;
    *o++ = val >> 8;
    *o++ = val;
    *opt = o;
}
Referenced by dhcp_server_process().
opt_write_u8()
static void opt_write_u8 (uint8_t ** opt, uint8_t cmd, uint8_t val) static
{
    uint8_t *o = *opt;
    *o++ = cmd;
    *o++ = 1;
    *o++ = val;
    *opt = o;
}
Referenced by dhcp_server_process().