GatorGrid: libraries/dnsserver/dnsserver.h File Reference
dnsserver.h File Reference
#include "lwip/ip_addr.h"
Classes
struct dns_server_t_
Typedefs
typedef struct dns_server_t_ dns_server_t
Functions
void dns_server_init (dns_server_t *d, ip_addr_t *ip)
void dns_server_deinit (dns_server_t *d)
Typedef Documentation
dns_server_t
typedef struct dns_server_t_ dns_server_t
Copyright (c) 2022 Raspberry Pi (Trading) Ltd.
SPDX-License-Identifier: BSD-3-Clause
Function Documentation
dns_server_deinit()
void dns_server_deinit (dns_server_t * d)
{
    dns_socket_free(&d->udp);
}
References dns_socket_free(), and dns_server_t_::udp.
dns_server_init()
void dns_server_init (dns_server_t * d, ip_addr_t * ip)
{
    if (dns_socket_new_dgram(&d->udp, d, dns_server_process) != ERR_OK) {
        DEBUG_printf("dns server failed to start\n");
        return;
    }
    if (dns_socket_bind(&d->udp, 0, PORT_DNS_SERVER) != ERR_OK) {
        DEBUG_printf("dns server failed to bind\n");
        return;
    }
    ip_addr_copy(d->ip, *ip);
    DEBUG_printf("dns server listening on port %d\n", PORT_DNS_SERVER);
}
References DEBUG_printf, dns_server_process(), dns_socket_bind(), dns_socket_new_dgram(), dns_server_t_::ip, PORT_DNS_SERVER, and dns_server_t_::udp.