GatorGrid: libraries/MeshNode/MeshNodeSTA.cpp File Reference
MeshNodeSTA.cpp File Reference
#include "libraries/SPI/SPI.hpp"
#include "MeshNode.hpp"
#include "Messages.hpp"
#include <random>
#include <ctime>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <sstream>
#include "pico/cyw43_arch.h"
#include "pico/stdlib.h"
#include "lwip/pbuf.h"
#include "lwip/tcp.h"
#include "dhcpserver.h"
#include "dnsserver.h"
#include "hardware/vreg.h"
#include "hardware/clocks.h"
Classes
struct TCP_CLIENT_T_
Macros
#define TCP_PORT 4242
#define DEBUG_printf printf
#define BUF_SIZE 2048
#define TEST_ITERATIONS 10
#define POLL_TIME_S 5
#define DUMP_BYTES dump_bytes
Typedefs
typedef struct TCP_CLIENT_T_ TCP_CLIENT_T
Functions
static void dump_bytes (const uint8_t *bptr, uint32_t len)
static err_t tcp_client_close (void *arg)
static err_t tcp_result (void *arg, int status)
static err_t tcp_client_sent (void *arg, struct tcp_pcb *tpcb, u16_t len)
static err_t tcp_client_connected (void *arg, struct tcp_pcb *tpcb, err_t err)
static err_t tcp_client_poll (void *arg, struct tcp_pcb *tpcb)
static void tcp_client_err (void *arg, err_t err)
err_t tcp_client_recv (void *arg, struct tcp_pcb *tpcb, struct pbuf *p, err_t err)
static bool tcp_client_open (void *arg)
static TCP_CLIENT_T * tcp_client_init (void)
int extract_id (const char *ssid)
Macro Definition Documentation
BUF_SIZE
#define BUF_SIZE 2048
DEBUG_printf
#define DEBUG_printf printf
DUMP_BYTES
#define DUMP_BYTES dump_bytes
POLL_TIME_S
#define POLL_TIME_S 5
TCP_PORT
#define TCP_PORT 4242
TEST_ITERATIONS
#define TEST_ITERATIONS 10
Typedef Documentation
TCP_CLIENT_T
typedef struct TCP_CLIENT_T_ TCP_CLIENT_T
Function Documentation
dump_bytes()
static void dump_bytes (const uint8_t * bptr, uint32_t len) static
{
     unsigned int i = 0;
     printf("dump_bytes %d", len);
     for (i = 0; i < len;) {
         if ((i & 0x0f) == 0) {
             printf("\n");
         } else if ((i & 0x07) == 0) {
             printf(" ");
         }
         printf("%02x ", bptr[i++]);
     }
     printf("\n");
 }
extract_id()
int extract_id (const char * ssid)
{
    // Find the position of ':'
    char *id_str = strchr(ssid, ':');
    if (id_str && *(id_str + 1)) {
        id_str++; // Move past ':'
        // Print extracted string for debugging
        //printf("Extracted ID string: %s\n", id_str);
        // Convert it to an integer
        int id = strtol(id_str, NULL, 16); // Assuming it's hexadecimal
        //printf("Converted ID: %d (Hex to Decimal)\n", id);
        return id;
    } else {
        printf("Invalid SSID format: %s\n", ssid);
        return -1;
    }
}
tcp_client_close()
static err_t tcp_client_close (void * arg) static
{
    STANode* node = (STANode*)arg;
    TCP_CLIENT_T *state = node->state;
    err_t err = ERR_OK;
    if (state->tcp_pcb != NULL) {
        tcp_arg(state->tcp_pcb, NULL);
        tcp_poll(state->tcp_pcb, NULL, 0);
        tcp_sent(state->tcp_pcb, NULL);
        tcp_recv(state->tcp_pcb, NULL);
        tcp_err(state->tcp_pcb, NULL);
        err = tcp_close(state->tcp_pcb);
        if (err != ERR_OK) {
            DEBUG_printf("close failed %d, calling abort\n", err);
            tcp_abort(state->tcp_pcb);
            err = ERR_ABRT;
        }
        state->tcp_pcb = NULL;
    }
    return err;
}
References DEBUG_printf, STANode::state, and TCP_CLIENT_T_::tcp_pcb.
Referenced by STANode::send_string_data(), and tcp_result().
tcp_client_connected()
static err_t tcp_client_connected (void * arg, struct tcp_pcb * tpcb, err_t err) static
{
    STANode* node = (STANode*)arg;
    TCP_CLIENT_T *state = node->state;
    if (err != ERR_OK) {
        printf("connect failed %d\n", err);
        return tcp_result(arg, err);
    }
    state->connected = true;
    DEBUG_printf("Waiting for response from server...\n");
    return ERR_OK;
}
References TCP_CLIENT_T_::connected, DEBUG_printf, STANode::state, and tcp_result().
Referenced by tcp_client_open().
tcp_client_err()
static void tcp_client_err (void * arg, err_t err) static
{
    if (err != ERR_ABRT) {
        DEBUG_printf("tcp_client_err %d\n", err);
        tcp_result(arg, err);
    }
}
References DEBUG_printf, and tcp_result().
Referenced by tcp_client_open().
tcp_client_init()
static TCP_CLIENT_T * tcp_client_init (void) static
{
    TCP_CLIENT_T *state = (TCP_CLIENT_T*)calloc(1, sizeof(TCP_CLIENT_T));
    if (!state) {
        DEBUG_printf("failed to allocate state\n");
        return NULL;
    }
    ip4addr_aton("192.168.4.1", &state->remote_addr);
    return state;
}
References DEBUG_printf, and TCP_CLIENT_T_::remote_addr.
Referenced by STANode::send_string_data(), and STANode::tcp_init().
tcp_client_open()
static bool tcp_client_open (void * arg) static
{
    STANode* node = (STANode*)arg;
    TCP_CLIENT_T *state = node->state;
    printf("Connecting to %s port %u\n", ip4addr_ntoa(&state->remote_addr), TCP_PORT);
    state->tcp_pcb = tcp_new_ip_type(IP_GET_TYPE(&state->remote_addr));
    if (!state->tcp_pcb) {
        printf("failed to create pcb\n");
        return false;
    }
    tcp_arg(state->tcp_pcb, node);
    //tcp_poll(state->tcp_pcb, tcp_client_poll, POLL_TIME_S * 2);
    tcp_sent(state->tcp_pcb, tcp_client_sent);
    tcp_recv(state->tcp_pcb, tcp_client_recv);
    tcp_err(state->tcp_pcb, tcp_client_err);
    state->buffer_len = 0;
    // cyw43_arch_lwip_begin/end should be used around calls into lwIP to ensure correct locking.
    // You can omit them if you are in a callback from lwIP. Note that when using pico_cyw_arch_poll
    // these calls are a no-op and can be omitted, but it is a good practice to use them in
    // case you switch the cyw43_arch type later.
    cyw43_arch_lwip_begin();
    err_t err = tcp_connect(state->tcp_pcb, &state->remote_addr, TCP_PORT, tcp_client_connected);
    cyw43_arch_lwip_end();
    return err == ERR_OK;
}
References TCP_CLIENT_T_::buffer_len, TCP_CLIENT_T_::remote_addr, STANode::state, tcp_client_connected(), tcp_client_err(), tcp_client_recv(), tcp_client_sent(), TCP_CLIENT_T_::tcp_pcb, and TCP_PORT.
Referenced by STANode::send_string_data(), and STANode::tcp_init().
tcp_client_poll()
static err_t tcp_client_poll (void * arg, struct tcp_pcb * tpcb) static
{
    //DEBUG_printf("tcp_client_poll\n");
    return tcp_result(arg, -1); // no response is an error?
}
References tcp_result().
tcp_client_recv()
err_t tcp_client_recv (void * arg, struct tcp_pcb * tpcb, struct pbuf * p, err_t err)
{
    STANode* node = (STANode*)arg;
    TCP_CLIENT_T *state = node->state;
    // Check for connection closed or error
    if (!p) {
        DEBUG_printf("Connection closed or error\n");
        return tcp_result(arg, 0); // Consider this a success as we've got a response
    }
    // This method is callback from lwIP, so cyw43_arch_lwip_begin is not required
    cyw43_arch_lwip_check();
    if (p->tot_len > 0) {
        DEBUG_printf("Received %d bytes, err %d\n", p->tot_len, err);
        // Copy data from pbuf to our buffer
        const uint16_t buffer_left = BUF_SIZE - state->buffer_len;
        uint16_t copy_len = p->tot_len > buffer_left ? buffer_left : p->tot_len;
        state->buffer_len += pbuf_copy_partial(p, state->buffer + state->buffer_len, copy_len, 0);
        // Print the received data for debugging
        // char received_data[256] = {0}; // Small buffer for displaying part of response
        // pbuf_copy_partial(p, received_data, p->tot_len > 255 ? 255 : p->tot_len, 0);
        // DEBUG_printf("Response: %s\n", received_data);
        // Acknowledge receipt of the data
        tcp_recved(tpcb, p->tot_len);
        // Consider this a success - we got a response
        // if (p->tot_len > 0) {
        //     pbuf_free(p);
        //     return tcp_result(arg, 0);
        // }
        uint32_t source_id = 0;
        bool ACK_flag = true;
        bool NAK_flag = false;
        bool self_reply = false;
        TCP_MESSAGE* msg = parseMessage(reinterpret_cast <uint8_t *>(state->buffer));
        if (!msg) {
            printf("Error: Unable to parse message (invalid buffer or unknown msg_id).\n");
            ACK_flag = false;
        } else {
            uint8_t msg_id = state->buffer[1];
            switch (msg_id) {
                case 0x00: {
                    TCP_INIT_MESSAGE* initMsg = static_cast<TCP_INIT_MESSAGE*>(msg);
                    //does stuff
                    printf("Received initialization message from node %u", initMsg->msg.source);
                    source_id =  initMsg->msg.source;
                    break;
                }
                case 0x01: {
                    TCP_DATA_MSG* dataMsg = static_cast<TCP_DATA_MSG*>(msg);
                    //does stuff
                    break;
                }
                case 0x02: {
                    TCP_DISCONNECT_MSG* discMsg = static_cast<TCP_DISCONNECT_MSG*>(msg);
                    //does stuff
                    break;
                }
                case 0x03: {
                    TCP_UPDATE_MESSAGE* updMsg = static_cast<TCP_UPDATE_MESSAGE*>(msg);
                    //does stuff
                    break;
                }
                case 0x04: {
                    puts("Got ACK");
                    TCP_ACK_MESSAGE* ackMsg = static_cast<TCP_ACK_MESSAGE*>(msg);
                    source_id = ackMsg->msg.source;
                    printf("Ack is from %08x and for %08x\n", ackMsg->msg.source, ackMsg->msg.dest);
                    if (ackMsg->msg.dest == node->get_NodeID()) {
                        self_reply = true;
                        puts("ACK is for me");
                        state->waiting_for_ack = false;
                    }
                    //does stuff
                    break;
                }
                case 0x05: {
                    TCP_NAK_MESSAGE* nakMsg = static_cast<TCP_NAK_MESSAGE*>(msg);
                    //does stuff
                    puts("Got NAK");
                    self_reply = true;
                    state->waiting_for_ack = false;
                    break;
                }
                default:
                    printf("Error: Unable to parse message (invalid buffer or unknown msg_id).\n");
                    ACK_flag = false;
                    // SEND NAK message
                    //TCP_NAK_MESSAGE nakMsg(node->get_NodeID(), msg_id ? msg_id : 0, 0);
                    break;
            }
        }
        if (ACK_flag && !self_reply){
            TCP_ACK_MESSAGE ackMsg(node->get_NodeID(), source_id, ackMsg.msg.len);
            node->send_tcp_data(ackMsg.get_msg(), ackMsg.get_len(), false);
            state->waiting_for_ack = true;
        } else if (NAK_flag) {
            // TODO: Update for error handling
            // identify the source from sender and send back?
            TCP_NAK_MESSAGE nakMsg(node->get_NodeID(), 0, 0);
            node->send_tcp_data(nakMsg.get_msg(), nakMsg.get_len(), false);
        }
        delete msg;
    }
    pbuf_free(p);
    return ERR_OK;
}
References BUF_SIZE, TCP_CLIENT_T_::buffer, TCP_CLIENT_T_::buffer_len, DEBUG_printf, TCP_ACK_MESSAGE::get_len(), TCP_NAK_MESSAGE::get_len(), TCP_ACK_MESSAGE::get_msg(), TCP_NAK_MESSAGE::get_msg(), MeshNode::get_NodeID(), TCP_INIT_MESSAGE::msg, TCP_ACK_MESSAGE::msg, parseMessage(), STANode::send_tcp_data(), STANode::state, tcp_result(), and TCP_CLIENT_T_::waiting_for_ack.
Referenced by tcp_client_open().
tcp_client_sent()
static err_t tcp_client_sent (void * arg, struct tcp_pcb * tpcb, u16_t len) static
{
    STANode* node = (STANode*)arg;
    TCP_CLIENT_T *state = node->state;
    DEBUG_printf("tcp_client_sent %u\n", len);
    state->sent_len += len;
    if (state->sent_len >= BUF_SIZE) {
        state->run_count++;
        if (state->run_count >= TEST_ITERATIONS) {
            tcp_result(arg, 0);
            return ERR_OK;
        }
        // We should receive a new buffer from the server
        state->buffer_len = 0;
        state->sent_len = 0;
        DEBUG_printf("Waiting for buffer from server\n");
    }
    return ERR_OK;
}
References BUF_SIZE, TCP_CLIENT_T_::buffer_len, DEBUG_printf, TCP_CLIENT_T_::run_count, TCP_CLIENT_T_::sent_len, STANode::state, tcp_result(), and TEST_ITERATIONS.
Referenced by tcp_client_open().
tcp_result()
static err_t tcp_result (void * arg, int status) static
{
    STANode* node = (STANode*)arg;
    TCP_CLIENT_T *state = node->state;
    if (status == 0) {
        DEBUG_printf("Response back gotten\n");
    } else {
        DEBUG_printf("Did not receive a response back!\n");
    }
    state->complete = true;
    return tcp_client_close(arg);
}
References TCP_CLIENT_T_::complete, DEBUG_printf, STANode::state, and tcp_client_close().
Referenced by tcp_client_connected(), tcp_client_err(), tcp_client_poll(), tcp_client_recv(), tcp_client_sent(), and STANode::tcp_init().