GatorGrid: libraries/MeshNode/Messages.hpp File Reference
Messages.hpp File Reference
#include <cstdint>
#include <cstring>
Classes
class TCP_MESSAGE
class TCP_INIT_MESSAGE
class TCP_DATA_MSG
class TCP_DISCONNECT_MSG
class TCP_UPDATE_MESSAGE
class TCP_ACK_MESSAGE
class TCP_NAK_MESSAGE
Functions
TCP_MESSAGE * parseMessage (uint8_t *data)
Takes in some tcp message buffer and returns a pointer to a new TCP_MESSAGE.
Function Documentation
parseMessage()
TCP_MESSAGE * parseMessage (uint8_t * data)
Takes in some tcp message buffer and returns a pointer to a new TCP_MESSAGE.
Parameters
data buffer recieved over tcp
Returns
TCP_MESSAGE* !!USER MUST DELETE!!
{
    //printf("Called parseMessage()");
    uint8_t msg_id = data[1];
    size_t data_len = *(reinterpret_cast<uint16_t*>(data+2));
    if (data_len < 4) {
        return nullptr;
    }
    switch (msg_id) {
        case 0x00: {  // TCP_INIT_MESSAGE
            if (data_len < sizeof(TCP_MESSAGE::tcp_init_msg_t))
                return nullptr;
            const auto* rawInit = reinterpret_cast<const TCP_MESSAGE::tcp_init_msg_t*>(data);
            TCP_INIT_MESSAGE* msg = new TCP_INIT_MESSAGE(rawInit->source);
            msg->set_msg((void*)data);
            return msg;
        }
        case 0x01: {  // TCP_DATA_MSG
            const auto* rawData = reinterpret_cast<const TCP_MESSAGE::tcp_data_msg_t*>(data);
            TCP_DATA_MSG* msg = new TCP_DATA_MSG(rawData->source, rawData->dest);
            msg->set_msg((void*)data);
            return msg;
        }
        case 0x02: {  // TCP_DISCONNECT_MSG
            if (data_len < sizeof(TCP_MESSAGE::tcp_disconnect_msg_t))
                return nullptr;
            const auto* rawDisc = reinterpret_cast<const TCP_MESSAGE::tcp_disconnect_msg_t*>(data);
            TCP_DISCONNECT_MSG* msg = new TCP_DISCONNECT_MSG(rawDisc->source);
            msg->set_msg((void*)data);
            return msg;
        }
        case 0x03: {  // TCP_UPDATE_MESSAGE
            if (data_len < sizeof(TCP_MESSAGE::tcp_update_msg_t))
                return nullptr;
            const auto* rawUpdate = reinterpret_cast<const TCP_MESSAGE::tcp_update_msg_t*>(data);
            TCP_UPDATE_MESSAGE* msg = new TCP_UPDATE_MESSAGE(rawUpdate->source);
            msg->set_msg((void*)data);
            return msg;
        }
        case 0x04: {  // TCP_ACK_MESSAGE
            if (data_len < sizeof(TCP_MESSAGE::tcp_acknowledge_msg_t))
                return nullptr;
            const auto* rawAck = reinterpret_cast<const TCP_MESSAGE::tcp_acknowledge_msg_t*>(data);
            TCP_ACK_MESSAGE* msg = new TCP_ACK_MESSAGE(rawAck->source, rawAck->dest, rawAck->bytes_received);
            msg->set_msg((void*)data);
            return msg;
        }
        case 0x05: {  // TCP_NAK_MESSAGE
            if (data_len < sizeof(TCP_MESSAGE::tcp_failed_msg_t))
                return nullptr;
            const auto* rawAck = reinterpret_cast<const TCP_MESSAGE::tcp_failed_msg_t*>(data);
            TCP_NAK_MESSAGE* msg = new TCP_NAK_MESSAGE(rawAck->source, rawAck->dest, rawAck->bytes_received);
            msg->set_msg((void*)data);
            return msg;
        }
        default:
            // Unknown msg_id
            return nullptr;
    }
}
References TCP_INIT_MESSAGE::set_msg(), TCP_DATA_MSG::set_msg(), TCP_DISCONNECT_MSG::set_msg(), TCP_UPDATE_MESSAGE::set_msg(), TCP_ACK_MESSAGE::set_msg(), TCP_NAK_MESSAGE::set_msg(), TCP_MESSAGE::tcp_acknowledge_msg_t, TCP_MESSAGE::tcp_data_msg_t, TCP_MESSAGE::tcp_disconnect_msg_t, TCP_MESSAGE::tcp_failed_msg_t, TCP_MESSAGE::tcp_init_msg_t, and TCP_MESSAGE::tcp_update_msg_t.
Referenced by STANode::handle_incoming_data(), and APNode::handle_incoming_data().