GatorGrid: Tests/SPI_MASTER_TEST.cpp File Reference
SPI_MASTER_TEST.cpp File Reference
#include "libraries/SPI/SPI.hpp"
#include <stdio.h>
Functions
int main ()
Function Documentation
main()
int main ()
           {
    stdio_init_all();
    // Delay to allow time to view serial monitor
    sleep_ms(10000);
    // Delay to wait for Slave to turn on and initialize
    sleep_ms(2000);
    SPI Master_Pico;
    // set as the master
    Master_Pico.SPI_init(true);
    uint8_t send_string[] = "Fortnite!";
    uint8_t recv_buffer[sizeof(send_string)] = {0};
    for (int i = 0; i<2 ;i++) {
        if(Master_Pico.SPI_is_write_available()){
            printf("Write available\n");
            Master_Pico.SPI_send_message(send_string, sizeof(send_string));
        }
        if(Master_Pico.SPI_is_read_available()){
            printf("Read available\n");
            Master_Pico.SPI_read_message(recv_buffer, sizeof(recv_buffer));
        }
        sleep_ms(1000);  // Wait before next transmission
    }
}
References SPI::SPI_init(), SPI::SPI_is_read_available(), SPI::SPI_is_write_available(), SPI::SPI_read_message(), and SPI::SPI_send_message().