GatorGrid: Tests/sta_two.cpp File Reference
sta_two.cpp File Reference
#include "pico/stdlib.h"
#include "libraries/MeshNode/MeshNode.hpp"
#include "libraries/MeshNode/Messages.hpp"
#include <cstdint>
#include <cstdio>
#include "pico/cyw43_arch.h"
#include <stdio.h>
#include <string.h>
#include "pico/binary_info.h"
#include "hardware/i2c.h"
Functions
int main ()
Variables
static int addr = 0x68
Function Documentation
main()
int main ()
           {
    stdio_init_all();
    // initial delay to allow user to look at the serial monitor
    sleep_ms(10000);
    // i2c_init(i2c_default, 400 * 1000);
    // gpio_set_function(PICO_DEFAULT_I2C_SDA_PIN, GPIO_FUNC_I2C);
    // gpio_set_function(PICO_DEFAULT_I2C_SCL_PIN, GPIO_FUNC_I2C);
    // gpio_pull_up(PICO_DEFAULT_I2C_SDA_PIN);
    // gpio_pull_up(PICO_DEFAULT_I2C_SCL_PIN);
    // bi_decl(bi_2pins_with_func(PICO_DEFAULT_I2C_SDA_PIN, PICO_DEFAULT_I2C_SCL_PIN, GPIO_FUNC_I2C));
    // mpu6050_reset();
    // int16_t acceleration[3], gyro[3], temp;
    //SPI spi;
    STANode node;
    node.init_sta_mode();
    node.start_sta_mode();
    cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, true);
    if (!node.scan_for_nodes()) {
        return 0;
    }
    printf("known nodes map size: %d\n", node.known_nodes.size());
    while (node.known_nodes.empty()) {
        //printf("known nodes map size: %d", node.known_nodes.size());
        if (!node.scan_for_nodes()) {
            return 0;
        }
    }
    sleep_ms(5000);
    printf("Left searching for nodes\n");
    while(!node.connect_to_network());
    if (!node.tcp_init()) {
        // Failed to init TCP connection
        while(true);
    }
   char format_string[50] = {0};
   int final_size;
   bool got_an_ack = false;
   int count = 0;
   uint32_t children_ids[4] = {};
    uint8_t number_of_children = 0;
    bool toggle = true;
    uint32_t send_count = 0;
    for (;;) {
        node.poll();
        // if (count == 500) {
        //     TCP_DATA_MSG msg(node.get_NodeID(), 0);
        //     msg.add_message(reinterpret_cast<uint8_t*>(&send_count), 4);
        //     node.send_msg(msg.get_msg());
        //     send_count++;
        // }
        if (count++ >= 1000) {
            cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, toggle);
            toggle = !toggle;
            if(!node.is_connected()) {
                printf("Not connected!\n");
            }
            node.tree.get_children(node.get_NodeID(), children_ids, number_of_children);
            printf("\n\nChildren:\n");
            for (int i = 0; i < number_of_children; i++) {
                printf("%u\t", children_ids[i]);
            }
            printf("\n");
            count = 0;
        }
        sleep_ms(1);
    }
    return 0;
}
References STANode::connect_to_network(), ChildrenTree::get_children(), MeshNode::get_NodeID(), STANode::init_sta_mode(), STANode::is_connected(), STANode::known_nodes, STANode::poll(), STANode::scan_for_nodes(), STANode::start_sta_mode(), STANode::tcp_init(), toggle, and STANode::tree.
Variable Documentation
addr
int addr = 0x68 static