GatorGrid: Tests/uart.cpp File Reference
uart.cpp File Reference
#include "libraries/UART/UART.hpp"
Functions
int main ()
Function Documentation
main()
int main ()
           {
    stdio_init_all();
    PicoUART uart;
    uart.picoUARTInit();
    uart.picoUARTInterruptInit();
    const char* testMessage = "Hello, UART!\n";
    uart.sendMessage(testMessage);
    while (true) {
        // Main loop can perform other tasks
        sleep_ms(1000);
    }
    return 0;
}
References PicoUART::picoUARTInit(), PicoUART::picoUARTInterruptInit(), and PicoUART::sendMessage().