GatorGrid: APNode Class Reference
APNode Class Reference
#include <MeshNode.hpp>
Public Member Functions
APNode ()
APNode (uint32_t id)
~APNode ()
bool init_ap_mode ()
bool start_ap_mode ()
void stop_ap_mode ()
void poll (unsigned int timeout_ms=1000)
char * get_client_data (int ID)
bool has_client_data (int ID)
bool check_all_client_data ()
void set_ap_credentials (char name[32], const char *pwd)
int get_node_id ()
void set_node_id (int ID)
void server_start ()
bool server_running ()
int number_of_messages ()
err_t send_data (uint32_t send_id, ssize_t len, uint8_t *buf)
bool send_tcp_data (uint32_t id, tcp_pcb *client_pcb, uint8_t *data, uint32_t size)
struct data digest_data ()
bool handle_incoming_data (unsigned char *buffer, tcp_pcb *tpcb, struct pbuf *p)
Public Member Functions inherited from MeshNode
MeshNode ()
virtual ~MeshNode ()
void set_NodeID (uint32_t ID)
uint32_t get_NodeID ()
void seed_rand ()
Public Attributes
TCP_SERVER_T * state
bool running
char ap_name [32]
const char * password = "password"
RingBuffer rb
ChildrenTree tree
SPI Master_Pico
std::vector< void * > connections
std::map< int, std::string > client_results
std::map< int, bool > client_results_flag
std::map< uint32_t, tcp_pcb * > client_tpcbs
Constructor & Destructor Documentation
APNode() [1/2]
APNode::APNode ()
               : state(nullptr), running(false), password("password"), rb(10), tree(get_NodeID()), Master_Pico()  {
    snprintf(ap_name, sizeof(ap_name), "GatorGrid_Node:%08X", get_NodeID());
    Master_Pico.SPI_init(true);
}
References ap_name, MeshNode::get_NodeID(), Master_Pico, and SPI::SPI_init().
APNode() [2/2]
APNode::APNode (uint32_t id)
                          : state(nullptr), running(false), password("password"), rb(10), tree(id), Master_Pico()  {
    set_NodeID(id);
    snprintf(ap_name, sizeof(ap_name), "GatorGrid_Node:%08X", get_NodeID());
    Master_Pico.SPI_init(true);
}
References ap_name, MeshNode::get_NodeID(), Master_Pico, MeshNode::set_NodeID(), and SPI::SPI_init().
~APNode()
APNode::~APNode ()
               {
    // Make sure AP mode is stopped
    stop_ap_mode();
    // Free the state if it exists
    if (state) {
        free(state);
        state = nullptr;
    }
    // Deinitialize the driver
    cyw43_arch_deinit();
}
References state, and stop_ap_mode().
Member Function Documentation
check_all_client_data()
bool APNode::check_all_client_data ()
digest_data()
struct data APNode::digest_data ()
{
    return this->rb.digest();
}
Referenced by main().
get_client_data()
char * APNode::get_client_data (int ID)
get_node_id()
int APNode::get_node_id ()
                       {
    return get_NodeID();
}
References MeshNode::get_NodeID().
Referenced by main(), and start_ap_mode().
handle_incoming_data()
bool APNode::handle_incoming_data (unsigned char * buffer, tcp_pcb * tpcb, struct pbuf * p)
{
    bool ACK_flag = true;
    bool NAK_flag = false;
    bool update_flag = false;
    uint8_t error = 0;
    // tcp_init_msg_t *init_msg_str = reinterpret_cast <tcp_init_msg_t *>(state->buffer_recv);
    // clients_map[tpcb].id = init_msg_str->source;
    //DEBUG_printf("ID RECV FROM INIT MESSAGE: %08X\n", clients_map[tpcb].id);
    // uint32_t test = ((APNode*)(state->ap_node))->get_NodeID();
    //DEBUG_printf("CURRENT NODE ID: %08X\n", test);
    puts("HANDLE DUMP");\
    dump_bytes(buffer, 100);
    // TCP_INIT_MESSAGE init_msg(((APNode*)(state->ap_node))->get_NodeID());
    TCP_MESSAGE* msg = parseMessage(reinterpret_cast <uint8_t *>(state->buffer_recv));
    uint8_t msg_id = 0xFF;
    if (!msg) {
       DEBUG_printf("Error: Unable to parse message (invalid buffer or unknown msg_id).\n");
        ACK_flag = false;
    } else {
        // TODO: Handle error checks for messages
        msg_id = buffer[1];
        //DUMP_BYTES(state->buffer_recv, 2048);
        switch (msg_id) {
            case 0x00: {
                TCP_INIT_MESSAGE* initMsg = static_cast<TCP_INIT_MESSAGE*>(msg);
               DEBUG_printf("Received initialization message from node %u", initMsg->msg.source);
                //does stuff
                // Set init node ID
                if(clients_map[tpcb].id_recved == false) {
                    ACK_flag = true;
                    clients_map[tpcb].id_recved = true;
                    clients_map[tpcb].id = initMsg->msg.source;
                }
                tree.add_child(initMsg->msg.source);
                // Insert into map of IDs to TPCB
                client_tpcbs.insert({clients_map[tpcb].id, tpcb});
                update_flag = true;
                break;
            }
            case 0x01: {
                TCP_DATA_MSG* dataMsg = static_cast<TCP_DATA_MSG*>(msg);
                // Store messages in a ring buffer
                puts("Got data message");
               DEBUG_printf("Testing dataMsg, len:%u, source:%08x, dest:%08x\n",dataMsg->msg.msg_len, dataMsg->msg.source, dataMsg->msg.dest);
                if (dataMsg->msg.dest == get_NodeID()) {
                    rb.insert(dataMsg->msg.msg,dataMsg->msg.msg_len, dataMsg->msg.source, dataMsg->msg.dest);
                    DEBUG_printf("Successfully inserted into ring buffer\n");
                    ACK_flag = true;
                    break;
                } else {
                    uint32_t dest;
                   DEBUG_printf("Message was not for me, was for dest:%08x\n", dataMsg->msg.dest);
                    // if(!tree.find_path_parent(dataMsg->msg.dest, &dest)) {
                    //     DEBUG_printf("Count not find path to parent\n");
                    //     ACK_flag = false;
                    //     //NAK_flag = true;
                    //     error = 0x01; // TODO make enum for errors (no node in tree)
                    //     TCP_NAK_MESSAGE nakMsg(get_NodeID(), clients_map[tpcb].id, p->tot_len);
                    //     nakMsg.set_error(error);
                    //     send_tcp_data(dataMsg->msg.source, client_tpcbs.at(dataMsg->msg.source), nakMsg.get_msg(), nakMsg.get_len());
                    //     break;
                    // }
                    // DEBUG_printf("Found path to parent, starts with %u\n", dest);
                    if (client_tpcbs.find(dataMsg->msg.dest) == client_tpcbs.end()) {
                        ACK_flag = false;
                        //NAK_flag = true;
                        error = 0x02; // TODO make enum for errors (id not in connected clients)
                        TCP_NAK_MESSAGE nakMsg(get_NodeID(), clients_map[tpcb].id, p->tot_len);
                        nakMsg.set_error(error);
                        send_tcp_data(dataMsg->msg.source, client_tpcbs.at(dataMsg->msg.source), nakMsg.get_msg(), nakMsg.get_len());
                        break;
                    }
                    ACK_flag = false;
                    DEBUG_printf("Forwarding message to node\n");
                    send_tcp_data(dataMsg->msg.dest, client_tpcbs.at(dataMsg->msg.dest), dataMsg->get_msg(), dataMsg->get_len());
                    break;
                }
            }
            case 0x02: {
                TCP_DISCONNECT_MSG* discMsg = static_cast<TCP_DISCONNECT_MSG*>(msg);
                //does stuff
                break;
            }
            case 0x03: {
                TCP_UPDATE_MESSAGE* updMsg = static_cast<TCP_UPDATE_MESSAGE*>(msg);
                //does stuff
                break;
            }
            case 0x04: {
                TCP_ACK_MESSAGE* ackMsg = static_cast<TCP_ACK_MESSAGE*>(msg);
                //does stuff
                // Do not need to respond to acks
                if (ackMsg->msg.dest == get_NodeID()) {
                    //rb.insert(dataMsg->msg.msg,dataMsg->msg.msg_len, dataMsg->msg.source, dataMsg->msg.dest);
                    ACK_flag = false;
                } else {
                    uint32_t dest;
                   DEBUG_printf("Message was not for me, was for dest:%08x\n", ackMsg->msg.dest);
                    // if(!tree.find_path_parent(ackMsg->msg.dest, &dest)) {
                    //     ACK_flag = false;
                    //     NAK_flag = true;
                    //     error = 0x01; // TODO make enum for errors (no node in tree)
                    //     break;
                    // }
                    if (client_tpcbs.find(ackMsg->msg.dest) == client_tpcbs.end()) {
                        ACK_flag = false;
                        //NAK_flag = true;
                        error = 0x02; // TODO make enum for errors (id not in connected clients)
                        TCP_NAK_MESSAGE nakMsg(get_NodeID(), clients_map[tpcb].id, p->tot_len);
                        nakMsg.set_error(error);
                        send_tcp_data(ackMsg->msg.source, client_tpcbs.at(ackMsg->msg.source), nakMsg.get_msg(), nakMsg.get_len());
                        break;
                    }
                    ACK_flag = false;
                    send_tcp_data(ackMsg->msg.dest, client_tpcbs.at(ackMsg->msg.dest), ackMsg->get_msg(), ackMsg->get_len());
                }
                break;
            }
            case 0x05: {
                TCP_NAK_MESSAGE* nakMsg = static_cast<TCP_NAK_MESSAGE*>(msg);
                ACK_flag = false;
                //does stuff
                break;
            }
            default:
               DEBUG_printf("Error: Unable to parse message (invalid buffer or unknown msg_id).\n");
                ACK_flag = false;
                break;
        }
    }
    if (update_flag) {
        puts("Update nodes called");
        /*puts("Broadcasting all connected nodes to each other");
        uint32_t ids[4] = {0};
        int j = 0;
        // Because this is a new node, resend the list of connected nodes to everyone
        for(auto i : client_tpcbs) {
            ids[j] = i.first;
            j++;
        }
        TCP_UPDATE_MESSAGE updateMsg(get_NodeID());
        updateMsg.add_children(j, ids);
        for(auto i : client_tpcbs) {
            sleep_ms(20);
            send_tcp_data(i.first, i.second, updateMsg.get_msg(), updateMsg.get_len());
           DEBUG_printf("Sent update message to %08x\n", i.first);
        }*/
    }
    if (ACK_flag){
       DEBUG_printf("Sending ACK message to client %08x\n", clients_map[tpcb].id);
        // Assumption: clients_map[tpcb].id implies that any message worth acking isn't being forwarded and is originating from the intended node
        TCP_ACK_MESSAGE ackMsg(get_NodeID(), clients_map[tpcb].id, p->tot_len);
        send_tcp_data(clients_map[tpcb].id, tpcb, ackMsg.get_msg(), ackMsg.get_len());
        //send_tcp_data(ackMsg.get_msg(), ackMsg.get_len());
       DEBUG_printf("Sent ACK message to client %08x\n", clients_map[tpcb].id);
    } else if (NAK_flag) {
        // TODO: Update for error handling
        // identify the source from clients_map and send back?
        TCP_NAK_MESSAGE nakMsg(get_NodeID(), clients_map[tpcb].id, p->tot_len);
        nakMsg.set_error(error);
        send_tcp_data(clients_map[tpcb].id, tpcb, nakMsg.get_msg(), nakMsg.get_len());
        //send_tcp_data(nakMsg.get_msg(), nakMsg.get_len());
        delete msg;
        return false;
    }
    delete msg;
    return true;
}
References ChildrenTree::add_child(), TCP_SERVER_T_::buffer_recv, client_tpcbs, clients_map, DEBUG_printf, TCP_DATA_MSG::get_len(), TCP_ACK_MESSAGE::get_len(), TCP_NAK_MESSAGE::get_len(), TCP_DATA_MSG::get_msg(), TCP_ACK_MESSAGE::get_msg(), TCP_NAK_MESSAGE::get_msg(), MeshNode::get_NodeID(), RingBuffer::insert(), TCP_INIT_MESSAGE::msg, TCP_DATA_MSG::msg, TCP_ACK_MESSAGE::msg, parseMessage(), rb, send_tcp_data(), TCP_NAK_MESSAGE::set_error(), state, and tree.
Referenced by tcp_server_recv().
has_client_data()
bool APNode::has_client_data (int ID)
init_ap_mode()
bool APNode::init_ap_mode ()
{
    // Allocate the state of the TCP server if not already allocated
    if (!state) {
        state = (TCP_SERVER_T*)calloc(1, sizeof(TCP_SERVER_T));
        if (!state) {
            DEBUG_printf("failed to allocate state\n");
            return false;
        }
    }
    // Initialize the state
    state->complete = false;
    state->server_pcb = nullptr;
    state->ap_node = this;
    state->recv_len = 0;
    // Initialize the driver
    if (cyw43_arch_init()) {
        DEBUG_printf("failed to initialize cyw43 driver\n");
        return false;
    }
    return true;
}
References TCP_SERVER_T_::ap_node, TCP_SERVER_T_::complete, DEBUG_printf, TCP_SERVER_T_::recv_len, TCP_SERVER_T_::server_pcb, and state.
Referenced by main().
number_of_messages()
int APNode::number_of_messages ()
{
    return this->rb.get_size();
}
References RingBuffer::get_size(), and rb.
Referenced by main().
poll()
void APNode::poll (unsigned int timeout_ms = 1000)
{
    if (!running || !state) {
        return;
    }
    // Check if we should stop
    if (state->complete) {
        running = false;
        return;
    }
    // Handle polling operations based on the architecture
    #if PICO_CYW43_ARCH_POLL
    // If using poll architecture, check for work
    cyw43_arch_poll();
    // Wait for work or timeout
    cyw43_arch_wait_for_work_until(make_timeout_time_ms(timeout_ms));
    #else
    // If using interrupt architecture, just sleep
    sleep_ms(timeout_ms);
    #endif
}
References TCP_SERVER_T_::complete, running, and state.
send_data()
err_t APNode::send_data (uint32_t send_id, ssize_t len, uint8_t * buf)
{
    TCP_DATA_MSG msg(get_NodeID(), send_id);
    msg.add_message(buf, len);
    if (client_tpcbs.find(send_id) == client_tpcbs.end()){
        return -2;
    }
    tcp_pcb *client_pcb = client_tpcbs.at(send_id);
    if (!send_tcp_data(send_id, client_pcb, msg.get_msg(), msg.get_len()))
        return -1;
    return 0;
}
References TCP_DATA_MSG::add_message(), client_tpcbs, TCP_DATA_MSG::get_len(), TCP_DATA_MSG::get_msg(), MeshNode::get_NodeID(), and send_tcp_data().
send_tcp_data()
bool APNode::send_tcp_data (uint32_t id, tcp_pcb * client_pcb, uint8_t * data, uint32_t size)
{
    //uint8_t buffer[size] = {};
    // if (size > BUF_SIZE) { size = BUF_SIZE; }
    //memcpy(buffer, data, size);
    bool flag = false;
    dump_bytes(data, size);
    cyw43_arch_lwip_begin();
    // not entirely sure its supposed to be client_pcb
    //err_t err = tcp_write(state->client_pcb, (void*)buffer, size, TCP_WRITE_FLAG_COPY);
    //err_t err2 = tcp_output(state->client_pcb);
   DEBUG_printf("send_tcp_data: Destination ID %08x\n", id);
    err_t err = tcp_write(client_pcb, (void*)data, size, TCP_WRITE_FLAG_COPY);
    err_t err2 = tcp_output(client_pcb);
    if (err != ERR_OK) {
       DEBUG_printf("Message failed to write\n");
       DEBUG_printf("ERR: %d\n", err);
        flag = true;
    }
    if (err2 != ERR_OK) {
       DEBUG_printf("Message failed to be sent\n");
        flag = true;
    }
    cyw43_arch_lwip_end();
    if (flag)
      return false;
   DEBUG_printf("Successfully queued message\n");
    return true;
}
References DEBUG_printf, and dump_bytes().
Referenced by handle_incoming_data(), and send_data().
server_running()
bool APNode::server_running ()
{
    return !this->state->complete;
}
References TCP_SERVER_T_::complete, and state.
Referenced by main().
server_start()
void APNode::server_start ()
{
    run_tcp_server(state);
}
References run_tcp_server(), and state.
Referenced by main().
set_ap_credentials()
void APNode::set_ap_credentials (char name[32], const char * pwd)
{
    memcpy(ap_name, name, sizeof(ap_name));
    password = pwd;
}
References ap_name, and password.
set_node_id()
void APNode::set_node_id (int ID)
{
    // calls the base class function
    set_NodeID(ID);
}
References MeshNode::set_NodeID().
start_ap_mode()
bool APNode::start_ap_mode ()
{
    // Delay to ensure the masters starts after the slave
    sleep_ms(2000);
    Master_Pico.SPI_init(true);
    // Enable the AP mode on the driver
    cyw43_arch_enable_ap_mode(ap_name, password, CYW43_AUTH_WPA2_AES_PSK);
    //state = tcp_server_init();
    if (!state) {
        return false;
    }
    #if LWIP_IPV6
     #define IP(x) ((x).u_addr.ip4)
     #else
     #define IP(x) (x)
     #endif
 \
     ip4_addr_t mask;
     IP(state->gw).addr = PP_HTONL(CYW43_DEFAULT_IP_AP_ADDRESS);
     IP(mask).addr = PP_HTONL(CYW43_DEFAULT_IP_MASK);
     #undef IP
    // Start the DHCP server
    //dhcp_server_t dhcp_server;
    dhcp_server_init(&state->dhcp_server, &state->gw, &mask);
    //dns_server_init(&state->dns_server, &state->gw);
    // if (!tcp_server_open(state)) {
    //     DEBUG_printf("failed to open server\n");
    //     return false;
    // }
    if (!tcp_server_open(state)) {
        tcp_server_result(state, -1);
        return false;
    }
    // Send over node ID to STA
    while(!Master_Pico.SPI_is_write_available());
    uint32_t ID = this->get_node_id();
    Master_Pico.SPI_send_message((uint8_t*) &ID, sizeof(ID));
    running = true;
    return true;
}
References ap_name, TCP_SERVER_T_::dhcp_server, dhcp_server_init(), get_node_id(), TCP_SERVER_T_::gw, IP, Master_Pico, password, running, SPI::SPI_init(), SPI::SPI_is_write_available(), SPI::SPI_send_message(), state, tcp_server_open(), and tcp_server_result().
Referenced by main().
stop_ap_mode()
void APNode::stop_ap_mode ()
{
    if (!running) {
        return;
    }
    // Disable the AP mode
    cyw43_arch_lwip_begin();
    cyw43_arch_disable_ap_mode();
    cyw43_arch_lwip_end();
    // Close the TCP server
    if (state && state->server_pcb) {
        tcp_server_close(state);
    }
    running = false;
}
References running, TCP_SERVER_T_::server_pcb, state, and tcp_server_close().
Referenced by ~APNode().
Member Data Documentation
ap_name
char APNode::ap_name[32]
Referenced by APNode(), APNode(), set_ap_credentials(), and start_ap_mode().
client_results
std::map<int, std::string> APNode::client_results
client_results_flag
std::map<int, bool> APNode::client_results_flag
client_tpcbs
std::map<uint32_t, tcp_pcb*> APNode::client_tpcbs
Referenced by handle_incoming_data(), and send_data().
connections
std::vector<void*> APNode::connections
Master_Pico
SPI APNode::Master_Pico
Referenced by APNode(), APNode(), and start_ap_mode().
password
const char* APNode::password = "password"
Referenced by set_ap_credentials(), and start_ap_mode().
rb
RingBuffer APNode::rb
Referenced by handle_incoming_data(), and number_of_messages().
running
bool APNode::running
Referenced by poll(), start_ap_mode(), and stop_ap_mode().
state
TCP_SERVER_T* APNode::state
Referenced by handle_incoming_data(), init_ap_mode(), poll(), server_running(), server_start(), start_ap_mode(), stop_ap_mode(), tcp_server_close(), tcp_server_result(), tcp_server_send_data(), tcp_server_sent(), and ~APNode().
tree
ChildrenTree APNode::tree
Referenced by handle_incoming_data().
The documentation for this class was generated from the following files:
libraries/MeshNode/MeshNode.hpp
libraries/MeshNode/MeshNodeAP.cpp