GatorGrid: TCP_DATA_MSG Class Reference
TCP_DATA_MSG Class Reference
#include <Messages.hpp>
Public Member Functions
TCP_DATA_MSG (uint32_t src_id, uint32_t dest_id)
void add_message (uint8_t msg_len, uint8_t *msg_i)
uint8_t * get_msg () override
uint16_t get_len () override
void set_msg (void *msg) override
Public Member Functions inherited from TCP_MESSAGE
TCP_MESSAGE (uint8_t priority)
~TCP_MESSAGE ()
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
struct __attribute__ ((__packed__))
Public Attributes
tcp_data_msg_t msg = {0}
Public Attributes inherited from TCP_MESSAGE
tcp_init_msg_t
tcp_update_msg_t
tcp_data_msg_t
tcp_disconnect_msg_t
tcp_acknowledge_msg_t
tcp_failed_msg_t
Additional Inherited Members
Protected Attributes inherited from TCP_MESSAGE
uint8_t priority
Constructor & Destructor Documentation
TCP_DATA_MSG()
TCP_DATA_MSG::TCP_DATA_MSG (uint32_t src_id, uint32_t dest_id) inline
                                                    : TCP_MESSAGE(0x7F) {
        msg.priority = priority;
        msg.msg_id = 0x01;
        msg.len = 14;
        msg.source = src_id;
        msg.dest = dest_id;
    }
References msg, and TCP_MESSAGE::priority.
Member Function Documentation
add_message()
void TCP_DATA_MSG::add_message (uint8_t msg_len, uint8_t * msg_i) inline
{
        memcpy(msg.msg, msg_i, msg_len > 2034 ? 2034 : msg_len);
        msg.msg_len = msg_len;
        msg.len += msg_len > 2034 ? 2034 : msg_len;
    }
References msg.
Referenced by main().
get_len()
uint16_t TCP_DATA_MSG::get_len () inline override virtual
Implements TCP_MESSAGE.
{
        return msg.len;
    }
References msg.
Referenced by main().
get_msg()
uint8_t * TCP_DATA_MSG::get_msg () inline override virtual
Implements TCP_MESSAGE.
{
        return reinterpret_cast<uint8_t*>(&msg);
    }
References msg.
Referenced by main().
set_msg()
void TCP_DATA_MSG::set_msg (void * msg) inline override virtual
Implements TCP_MESSAGE.
{
        this->msg = *(reinterpret_cast<tcp_data_msg_t*>(msg));
    }
References msg, and TCP_MESSAGE::tcp_data_msg_t.
Referenced by parseMessage().
Member Data Documentation
msg
tcp_data_msg_t TCP_DATA_MSG::msg = {0}
{0};
Referenced by add_message(), get_len(), get_msg(), set_msg(), TCP_DATA_MSG(), and tcp_server_recv().
The documentation for this class was generated from the following file:
libraries/MeshNode/Messages.hpp