GatorGrid: libraries/MeshNode/MeshNodeAP.cpp File Reference
MeshNodeAP.cpp File Reference
#include "MeshNode.hpp"
#include "Messages.hpp"
#include <random>
#include <ctime>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <sstream>
#include "../SPI/SPI.hpp"
#include "hardware/regs/rosc.h"
#include "hardware/regs/addressmap.h"
#include "pico/cyw43_arch.h"
#include "pico/stdlib.h"
#include "lwip/pbuf.h"
#include "lwip/tcp.h"
#include "dhcpserver.h"
#include "dnsserver.h"
#include "hardware/vreg.h"
#include "hardware/clocks.h"
Classes
struct TCP_CONNECT_STATE_T_
struct TCP_SERVER_T_
struct ClientConnection
Macros
#define TCP_PORT 4242
#define DEBUG_printf printf
#define BUF_SIZE 2048
#define TEST_ITERATIONS 10
#define POLL_TIME_S 5
#define DUMP_BYTES dump_bytes
#define IP(x) (x)
Typedefs
typedef struct TCP_CONNECT_STATE_T_ TCP_CONNECT_STATE_T
typedef struct TCP_SERVER_T_ TCP_SERVER_T
Functions
static void dump_bytes (const uint8_t *bptr, uint32_t len)
TCP_SERVER_T * tcp_server_init (void)
err_t tcp_server_close (void *arg)
err_t tcp_server_result (void *arg, int status)
err_t tcp_server_sent (void *arg, struct tcp_pcb *tpcb, u16_t len)
err_t tcp_server_send_data (void *arg, struct tcp_pcb *tpcb)
err_t tcp_server_recv (void *arg, struct tcp_pcb *tpcb, struct pbuf *p, err_t err)
err_t tcp_server_poll (void *arg, struct tcp_pcb *tpcb)
void tcp_server_err (void *arg, err_t err)
err_t tcp_server_accept (void *arg, struct tcp_pcb *client_pcb, err_t err)
bool tcp_server_open (void *arg)
void run_tcp_server (void *arg)
Variables
std::vector< ClientConnection > clients
std::map< tcp_pcb *, ClientConnection > clients_map
Macro Definition Documentation
BUF_SIZE
#define BUF_SIZE 2048
DEBUG_printf
#define DEBUG_printf printf
DUMP_BYTES
#define DUMP_BYTES dump_bytes
IP
#define IP (x) (x)
POLL_TIME_S
#define POLL_TIME_S 5
TCP_PORT
#define TCP_PORT 4242
TEST_ITERATIONS
#define TEST_ITERATIONS 10
Typedef Documentation
TCP_CONNECT_STATE_T
typedef struct TCP_CONNECT_STATE_T_ TCP_CONNECT_STATE_T
TCP_SERVER_T
typedef struct TCP_SERVER_T_ TCP_SERVER_T
Function Documentation
dump_bytes()
static void dump_bytes (const uint8_t * bptr, uint32_t len) static
{
     unsigned int i = 0;
     printf("dump_bytes %d", len);
     for (i = 0; i < len;) {
         if ((i & 0x0f) == 0) {
             printf("\n");
         } else if ((i & 0x07) == 0) {
             printf(" ");
         }
         printf("%02x ", bptr[i++]);
     }
     printf("\n");
 }
Referenced by dns_server_process(), and dns_socket_sendto().
run_tcp_server()
void run_tcp_server (void * arg)
{
    TCP_SERVER_T *state = (TCP_SERVER_T*)arg;
    if (!tcp_server_open(state)) {
        tcp_server_result(state, -1);
        return;
    }
    while(!state->complete) {
        // the following #ifdef is only here so this same example can be used in multiple modes;
        // you do not need it in your code
#if PICO_CYW43_ARCH_POLL
        // if you are using pico_cyw43_arch_poll, then you must poll periodically from your
        // main loop (not from a timer) to check for Wi-Fi driver or lwIP work that needs to be done.
        cyw43_arch_poll();
        // you can poll as often as you like, however if you have nothing else to do you can
        // choose to sleep until either a specified time, or cyw43_arch_poll() has work to do:
        cyw43_arch_wait_for_work_until(make_timeout_time_ms(1000));
#else
        // if you are not using pico_cyw43_arch_poll, then WiFI driver and lwIP work
        // is done via interrupt in the background. This sleep is just an example of some (blocking)
        // work you might be doing.
        sleep_ms(1000);
#endif
    }
    printf("Now freeing state\n");
    free(state);
}
References TCP_SERVER_T_::complete, tcp_server_open(), and tcp_server_result().
Referenced by APNode::server_start().
tcp_server_accept()
err_t tcp_server_accept (void * arg, struct tcp_pcb * client_pcb, err_t err)
{
    TCP_SERVER_T *state = (TCP_SERVER_T*)arg;
    if (err != ERR_OK || client_pcb == NULL) {
        DEBUG_printf("Failure in accept\n");
        tcp_server_result(arg, err);
        return ERR_VAL;
    }
    DEBUG_printf("Client connected\n");
    struct ClientConnection client;
    client.pcb = client_pcb;
    clients.push_back({client});
    clients_map.insert({client_pcb, client});
    state->client_pcb = client_pcb;
    tcp_arg(client_pcb, state);
    tcp_sent(client_pcb, tcp_server_sent);
    tcp_recv(client_pcb, tcp_server_recv);
    tcp_poll(client_pcb, tcp_server_poll, POLL_TIME_S * 2);
    tcp_err(client_pcb, tcp_server_err);
    //return tcp_server_send_data(arg, state->client_pcb);
    return ERR_OK;
}
References TCP_SERVER_T_::client_pcb, clients, clients_map, DEBUG_printf, ClientConnection::pcb, POLL_TIME_S, tcp_server_err(), tcp_server_poll(), tcp_server_recv(), tcp_server_result(), and tcp_server_sent().
Referenced by tcp_server_open().
tcp_server_close()
err_t tcp_server_close (void * arg)
{
    APNode* node = (APNode*)arg;
    TCP_SERVER_T *state = node->state;
    err_t err = ERR_OK;
    if (state->client_pcb != NULL) {
        tcp_arg(state->client_pcb, NULL);
        tcp_poll(state->client_pcb, NULL, 0);
        tcp_sent(state->client_pcb, NULL);
        tcp_recv(state->client_pcb, NULL);
        tcp_err(state->client_pcb, NULL);
        err = tcp_close(state->client_pcb);
        if (err != ERR_OK) {
            DEBUG_printf("close failed %d, calling abort\n", err);
            tcp_abort(state->client_pcb);
            err = ERR_ABRT;
        }
        state->client_pcb = NULL;
    }
    if (state->server_pcb) {
        tcp_arg(state->server_pcb, NULL);
        tcp_close(state->server_pcb);
        state->server_pcb = NULL;
    }
    return err;
}
References TCP_SERVER_T_::client_pcb, DEBUG_printf, TCP_SERVER_T_::server_pcb, and APNode::state.
Referenced by APNode::stop_ap_mode(), and tcp_server_result().
tcp_server_err()
void tcp_server_err (void * arg, err_t err)
{
    if (err != ERR_ABRT) {
        DEBUG_printf("tcp_client_err_fn %d\n", err);
        tcp_server_result(arg, err);
    }
}
References DEBUG_printf, and tcp_server_result().
Referenced by tcp_server_accept().
tcp_server_init()
TCP_SERVER_T * tcp_server_init (void)
{
    TCP_SERVER_T *state = (TCP_SERVER_T*)calloc(1, sizeof(TCP_SERVER_T));
    if (!state) {
        DEBUG_printf("failed to allocate state\n");
        return NULL;
    }
    return state;
}
References DEBUG_printf.
tcp_server_open()
bool tcp_server_open (void * arg)
{
    TCP_SERVER_T *state = (TCP_SERVER_T*)arg;
    DEBUG_printf("Starting server at %s on port %u\n", ip4addr_ntoa(netif_ip4_addr(netif_list)), TCP_PORT);
    struct tcp_pcb *pcb = tcp_new_ip_type(IPADDR_TYPE_ANY);
    if (!pcb) {
        DEBUG_printf("failed to create pcb\n");
        return false;
    }
    err_t err = tcp_bind(pcb, NULL, TCP_PORT);
    if (err) {
        DEBUG_printf("failed to bind to port %u\n", TCP_PORT);
        return false;
    }
    state->server_pcb = tcp_listen_with_backlog(pcb, 1);
    if (!state->server_pcb) {
        DEBUG_printf("failed to listen\n");
        if (pcb) {
            tcp_close(pcb);
        }
        return false;
    }
    tcp_arg(state->server_pcb, state);
    tcp_accept(state->server_pcb, tcp_server_accept);
    return true;
}
References DEBUG_printf, TCP_SERVER_T_::server_pcb, TCP_PORT, and tcp_server_accept().
Referenced by run_tcp_server(), and APNode::start_ap_mode().
tcp_server_poll()
err_t tcp_server_poll (void * arg, struct tcp_pcb * tpcb)
{
    DEBUG_printf("tcp_server_poll_fn\n");
    return ERR_OK;
    //return tcp_server_result(arg, -1); // no response is an error?
}
References DEBUG_printf.
Referenced by tcp_server_accept().
tcp_server_recv()
err_t tcp_server_recv (void * arg, struct tcp_pcb * tpcb, struct pbuf * p, err_t err)
{
    // APNode* node = (APNode*)arg;
    TCP_SERVER_T *state = (TCP_SERVER_T*)arg;
    APNode* node = (APNode*)state->ap_node;
    bool got_full_message = false;
    printf("Recv called\n");
    if (!p) {
        return tcp_server_result(arg, -1);
    }
    // this method is callback from lwIP, so cyw43_arch_lwip_begin is not required, however you
    // can use this method to cause an assertion in debug mode, if this method is called when
    // cyw43_arch_lwip_begin IS needed
    cyw43_arch_lwip_check();
    if (p->tot_len > 0) {
        DEBUG_printf("tcp_server_recv %d/%d err %d\n", p->tot_len, state->recv_len, err);
        // Receive the buffer
        const uint16_t buffer_left = BUF_SIZE - state->recv_len;
        //printf("before pbuf copy partial\n");
        state->recv_len += pbuf_copy_partial(p, state->buffer_recv + state->recv_len,
                                             p->tot_len > buffer_left ? buffer_left : p->tot_len, 0);
        //printf("after pbuf copy partial\n");
        tcp_recved(tpcb, p->tot_len);
        //printf("before tcp_recved\n");
        if(state->recv_len == 2048) {
            printf("SERVER DEBUG: GOT 2048\n");
            //got_full_message = true;
        } else {
            printf("SERVER DEBUG: Currently recv %d\n", state->recv_len);
        }
        if(clients_map.find(tpcb) != clients_map.end()) {
            printf("PCB FOUND\n");
        } else {
            printf("MAJOR ERROR CLIENT PCB NOT FOUND\n");
            return ERR_OK; // TODO: Change error handling
        }
        bool ACK_flag = true;
        bool NAK_flag = false;
        // tcp_init_msg_t *init_msg_str = reinterpret_cast <tcp_init_msg_t *>(state->buffer_recv);
        // clients_map[tpcb].id = init_msg_str->source;
        // printf("ID RECV FROM INIT MESSAGE: %08X\n", clients_map[tpcb].id);
        // uint32_t test = ((APNode*)(state->ap_node))->get_NodeID();
        // printf("CURRENT NODE ID: %08X\n", test);
        // TCP_INIT_MESSAGE init_msg(((APNode*)(state->ap_node))->get_NodeID());
        TCP_MESSAGE* msg = parseMessage(reinterpret_cast <uint8_t *>(state->buffer_recv));
        uint8_t msg_id = 0xFF;
        if (!msg) {
            printf("Error: Unable to parse message (invalid buffer or unknown msg_id).\n");
            ACK_flag = false;
        } else {
            // TODO: Handle error checks for messages
            msg_id = state->buffer_recv[1];
            //DUMP_BYTES(state->buffer_recv, 2048);
            switch (msg_id) {
                case 0x00: {
                    TCP_INIT_MESSAGE* initMsg = static_cast<TCP_INIT_MESSAGE*>(msg);
                    printf("Received initialization message from node %u", initMsg->msg.source);
                    //does stuff
                    // Set init node ID
                    if(clients_map[tpcb].id_recved == false) {
                        ACK_flag = true;
                        clients_map[tpcb].id_recved = true;
                        clients_map[tpcb].id = initMsg->msg.source;
                    }
                    break;
                }
                case 0x01: {
                    TCP_DATA_MSG* dataMsg = static_cast<TCP_DATA_MSG*>(msg);
                    // Store messages in a ring buffer
                    puts("Got data message");
                    printf("Testing dataMsg, len:%u, source:%08x, dest:%08x\n",dataMsg->msg.msg_len, dataMsg->msg.source, dataMsg->msg.dest);
                    node->rb.insert(dataMsg->msg.msg,dataMsg->msg.msg_len, dataMsg->msg.source, dataMsg->msg.dest);
                    printf("Successfully inserted into ring buffer\n");
                    break;
                }
                case 0x02: {
                    TCP_DISCONNECT_MSG* discMsg = static_cast<TCP_DISCONNECT_MSG*>(msg);
                    //does stuff
                    break;
                }
                case 0x03: {
                    TCP_UPDATE_MESSAGE* updMsg = static_cast<TCP_UPDATE_MESSAGE*>(msg);
                    //does stuff
                    break;
                }
                case 0x04: {
                    TCP_ACK_MESSAGE* ackMsg = static_cast<TCP_ACK_MESSAGE*>(msg);
                    //does stuff
                    // Do not need to respond to acks
                    ACK_flag = false;
                    break;
                }
                case 0x05: {
                    TCP_NAK_MESSAGE* nakMsg = static_cast<TCP_NAK_MESSAGE*>(msg);
                    //does stuff
                    break;
                }
                default:
                    printf("Error: Unable to parse message (invalid buffer or unknown msg_id).\n");
                    ACK_flag = false;
                    break;
            }
        }
        if (ACK_flag){
            // Assumption: clients_map[tpcb].id implies that any message worth acking isn't being forwarded and is originating from the intended node
            TCP_ACK_MESSAGE ackMsg(node->get_NodeID(), clients_map[tpcb].id, p->tot_len);
            node->send_tcp_data(ackMsg.get_msg(), ackMsg.get_len());
            printf("Sent ACK message to client %u", clients_map[tpcb].id);
        } else if (NAK_flag) {
            // TODO: Update for error handling
            // identify the source from clients_map and send back?
            TCP_NAK_MESSAGE nakMsg(node->get_NodeID(), clients_map[tpcb].id, p->tot_len);
            node->send_tcp_data(nakMsg.get_msg(), nakMsg.get_len());
        }
        delete msg;
        //tcp_server_send_data(arg, state->client_pcb);
        // for (int i = 0; i < 20; i++) {
        //     printf("recv buff[%d] == %02x\n", i, state->buffer_recv[i]);
        // }
    }
    // Reset the TCP buffer state or else data will just be appened to the state recv buffer
    state->recv_len = 0;
    pbuf_free(p);
    // Have we have received the whole buffer
    // if (state->recv_len == BUF_SIZE) {
    //     // check it matches
    //     if (memcmp(state->buffer_sent, state->buffer_recv, BUF_SIZE) != 0) {
    //         DEBUG_printf("buffer mismatch\n");
    //         return tcp_server_result(arg, -1);
    //     }
    //     DEBUG_printf("tcp_server_recv buffer ok\n");
    //     // Test complete?
    //     //state->run_count++;
    //     /*if (state->run_count >= TEST_ITERATIONS) {
    //         tcp_server_result(arg, 0);
    //         return ERR_OK;
    //     }*/
    //     // Send another buffer
    //     return ERR_OK;
    //     //return tcp_server_send_data(arg, state->client_pcb);
    // }
    return ERR_OK;
}
References TCP_SERVER_T_::ap_node, BUF_SIZE, TCP_SERVER_T_::buffer_recv, clients_map, DEBUG_printf, TCP_ACK_MESSAGE::get_len(), TCP_NAK_MESSAGE::get_len(), TCP_ACK_MESSAGE::get_msg(), TCP_NAK_MESSAGE::get_msg(), MeshNode::get_NodeID(), RingBuffer::insert(), TCP_INIT_MESSAGE::msg, TCP_DATA_MSG::msg, parseMessage(), APNode::rb, TCP_SERVER_T_::recv_len, APNode::send_tcp_data(), and tcp_server_result().
Referenced by tcp_server_accept().
tcp_server_result()
err_t tcp_server_result (void * arg, int status)
{
    APNode* node = (APNode*)arg;
    TCP_SERVER_T *state = node->state;
    if (status == 0) {
        DEBUG_printf("test success\n");
    } else {
        DEBUG_printf("test failed %d\n", status);
    }
    state->complete = true;
    return tcp_server_close(arg);
}
References TCP_SERVER_T_::complete, DEBUG_printf, APNode::state, and tcp_server_close().
Referenced by run_tcp_server(), APNode::start_ap_mode(), tcp_server_accept(), tcp_server_err(), tcp_server_recv(), and tcp_server_send_data().
tcp_server_send_data()
err_t tcp_server_send_data (void * arg, struct tcp_pcb * tpcb)
{
    APNode* node = (APNode*)arg;
    TCP_SERVER_T *state = node->state;
    /*for(int i=0; i< BUF_SIZE; i++) {
        state->buffer_sent[i] = rand();
    }*/
    state->sent_len = 0;
    DEBUG_printf("Writing %ld bytes to client\n", BUF_SIZE);
    // this method is callback from lwIP, so cyw43_arch_lwip_begin is not required, however you
    // can use this method to cause an assertion in debug mode, if this method is called when
    // cyw43_arch_lwip_begin IS needed
    cyw43_arch_lwip_check();
    err_t err = tcp_write(tpcb, state->buffer_sent, BUF_SIZE, TCP_WRITE_FLAG_COPY);
    if (err != ERR_OK) {
        DEBUG_printf("Failed to write data %d\n", err);
        return tcp_server_result(arg, -1);
    }
    return ERR_OK;
}
References BUF_SIZE, TCP_SERVER_T_::buffer_sent, DEBUG_printf, TCP_SERVER_T_::sent_len, APNode::state, and tcp_server_result().
tcp_server_sent()
err_t tcp_server_sent (void * arg, struct tcp_pcb * tpcb, u16_t len)
{
    APNode* node = (APNode*)arg;
    TCP_SERVER_T *state = node->state;
    DEBUG_printf("tcp_server_sent %u\n", len);
    state->sent_len += len;
    if (state->sent_len >= BUF_SIZE) {
        // We should get the data back from the client
        state->recv_len = 0;
        DEBUG_printf("Waiting for buffer from client\n");
    }
    return ERR_OK;
}
References BUF_SIZE, DEBUG_printf, TCP_SERVER_T_::recv_len, TCP_SERVER_T_::sent_len, and APNode::state.
Referenced by tcp_server_accept().
Variable Documentation
clients
std::vector<ClientConnection> clients
Referenced by tcp_server_accept().
clients_map
std::map<tcp_pcb *, ClientConnection> clients_map
Referenced by tcp_server_accept(), and tcp_server_recv().