GatorGrid: Tests/sta_test.cpp File Reference
sta_test.cpp File Reference
#include "pico/stdlib.h"
#include "libraries/MeshNode/MeshNode.hpp"
#include "libraries/MeshNode/Messages.hpp"
#include <cstdio>
#include "pico/cyw43_arch.h"
#include "pico/multicore.h"
Functions
int main ()
Function Documentation
main()
int main ()
           {
    stdio_init_all();
    // initial delay to allow user to look at the serial monitor
    sleep_ms(10000);
    // initiate everything
    //SPI spi;
    STANode node;
    node.init_sta_mode();
    node.start_sta_mode();
    cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, true);
    if (!node.scan_for_nodes()) {
        return 0;
    }
    printf("known nodes map size: %d\n", node.known_nodes.size());
    while (node.known_nodes.empty()) {
        //printf("known nodes map size: %d", node.known_nodes.size());
        if (!node.scan_for_nodes()) {
            return 0;
        }
    }
    printf("Left searching for nodes\n");
    if (node.connect_to_node(node.known_nodes.begin()->first)) {
        node.tcp_init();
    }
    sleep_ms(1000);
    for (int i = 0; i < 10; i++)
    {
        TCP_DATA_MSG msg(node.get_NodeID(), node.parent);
        uint8_t arr[] = "hello, this is message:  ";
        arr[24] = 48 + i;
        msg.add_message(25, arr);
        node.send_tcp_data(msg.get_msg(), msg.get_len(), false);
    }
    bool toggle = true;
    for (;;) {
        cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, toggle);
        toggle = !toggle;
        if(!node.is_connected()) {
            printf("Not connected!\n");
        }
        sleep_ms(5000);
    }
    return 0;
}
References TCP_DATA_MSG::add_message(), STANode::connect_to_node(), TCP_DATA_MSG::get_len(), TCP_DATA_MSG::get_msg(), MeshNode::get_NodeID(), STANode::init_sta_mode(), STANode::is_connected(), STANode::known_nodes, STANode::parent, STANode::scan_for_nodes(), STANode::send_tcp_data(), STANode::start_sta_mode(), and STANode::tcp_init().