GatorGrid: Tests/ap_two.cpp File Reference
ap_two.cpp File Reference
#include "pico/stdlib.h"
#include "libraries/MeshNode/MeshNode.hpp"
#include <cstdio>
#include "pico/cyw43_arch.h"
#include "pico/multicore.h"
Macros
#define DEBUG 1
Functions
int main ()
Variables
bool is_wifi_connected = false
Macro Definition Documentation
DEBUG
#define DEBUG 1
Function Documentation
main()
int main ()
           {
    // initiate everything
    stdio_init_all();
    // initial delay to allow user to look at the serial monitor
    sleep_ms(10000);
    //multicore_launch_core1(core1_entry);
    APNode node(2);
    printf("Init AP Mode\n");
    if (!node.init_ap_mode())
    {
        sleep_ms(1000);
    }
    printf("Starting AP Mode\n");
    if (!node.start_ap_mode()) {
        sleep_ms(1000);
    }
    printf("AP ID: %08x\n", node.get_NodeID());
    // if(spi.SPI_send_message(id, 4) != 1) {
    //     for (;;) { sleep_ms(1000); }
    // }
    bool toggle = true;
    while (node.server_running()) {
        //cyw43_arch_poll();
        // you can poll as often as you like, however if you have nothing else to do you can
        // choose to sleep until either a specified time, or cyw43_arch_poll() has work to do:
        //cyw43_arch_wait_for_work_until(make_timeout_time_ms(1000));
        if(node.number_of_messages() > 0) {
            puts("You got mail!");
            while(node.number_of_messages() != 0) {
                struct data tmp = node.digest_data();
                printf("Source: %08x\nData: \"%s\"\n", tmp.source, tmp.data);
            }
        }
        cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, toggle);
        toggle = !toggle;
        //printf("core print...");
        sleep_ms(1000);
    }
    for (;;) {
        puts("Exited");
        sleep_ms(1000);
    }
    return 0;
}
References data::data, APNode::digest_data(), MeshNode::get_NodeID(), APNode::init_ap_mode(), APNode::number_of_messages(), APNode::server_running(), data::source, and APNode::start_ap_mode().
Variable Documentation
is_wifi_connected
bool is_wifi_connected = false